// Generated by CIRCT firtool-1.138.0
module PrefixAbsDiff(
  input  io_a,
         io_b,
  output io_lt,
         io_absDiff
);

  assign io_lt = ~io_a & io_b;
  assign io_absDiff = io_a ^ io_b;
endmodule

