// Generated by CIRCT firtool-1.138.0
module PrefixAbsDiff(
  input  [49:0] io_a,
                io_b,
  output        io_lt,
  output [49:0] io_absDiff
);

  wire _GEN = ~(io_a[0]) & io_b[0];
  wire _absDiff_WIRE_0 = io_a[0] ^ io_b[0];
  wire _absDiff_T_2 = io_a[1] ^ io_b[1];
  wire _absDiff_T_4 = io_a[2] ^ io_b[2];
  wire _absDiff_T_6 = io_a[3] ^ io_b[3];
  wire _absDiff_T_8 = io_a[4] ^ io_b[4];
  wire _absDiff_T_10 = io_a[5] ^ io_b[5];
  wire _absDiff_T_12 = io_a[6] ^ io_b[6];
  wire _absDiff_T_14 = io_a[7] ^ io_b[7];
  wire _absDiff_T_16 = io_a[8] ^ io_b[8];
  wire _absDiff_T_18 = io_a[9] ^ io_b[9];
  wire _absDiff_T_20 = io_a[10] ^ io_b[10];
  wire _absDiff_T_22 = io_a[11] ^ io_b[11];
  wire _absDiff_T_24 = io_a[12] ^ io_b[12];
  wire _absDiff_T_26 = io_a[13] ^ io_b[13];
  wire _absDiff_T_28 = io_a[14] ^ io_b[14];
  wire _absDiff_T_30 = io_a[15] ^ io_b[15];
  wire _absDiff_T_32 = io_a[16] ^ io_b[16];
  wire _absDiff_T_34 = io_a[17] ^ io_b[17];
  wire _absDiff_T_36 = io_a[18] ^ io_b[18];
  wire _absDiff_T_38 = io_a[19] ^ io_b[19];
  wire _absDiff_T_40 = io_a[20] ^ io_b[20];
  wire _absDiff_T_42 = io_a[21] ^ io_b[21];
  wire _absDiff_T_44 = io_a[22] ^ io_b[22];
  wire _absDiff_T_46 = io_a[23] ^ io_b[23];
  wire _absDiff_T_48 = io_a[24] ^ io_b[24];
  wire _absDiff_T_50 = io_a[25] ^ io_b[25];
  wire _absDiff_T_52 = io_a[26] ^ io_b[26];
  wire _absDiff_T_54 = io_a[27] ^ io_b[27];
  wire _absDiff_T_56 = io_a[28] ^ io_b[28];
  wire _absDiff_T_58 = io_a[29] ^ io_b[29];
  wire _absDiff_T_60 = io_a[30] ^ io_b[30];
  wire _absDiff_T_62 = io_a[31] ^ io_b[31];
  wire _absDiff_T_64 = io_a[32] ^ io_b[32];
  wire _absDiff_T_66 = io_a[33] ^ io_b[33];
  wire _absDiff_T_68 = io_a[34] ^ io_b[34];
  wire _absDiff_T_70 = io_a[35] ^ io_b[35];
  wire _absDiff_T_72 = io_a[36] ^ io_b[36];
  wire _absDiff_T_74 = io_a[37] ^ io_b[37];
  wire _absDiff_T_76 = io_a[38] ^ io_b[38];
  wire _absDiff_T_78 = io_a[39] ^ io_b[39];
  wire _absDiff_T_80 = io_a[40] ^ io_b[40];
  wire _absDiff_T_82 = io_a[41] ^ io_b[41];
  wire _absDiff_T_84 = io_a[42] ^ io_b[42];
  wire _absDiff_T_86 = io_a[43] ^ io_b[43];
  wire _absDiff_T_88 = io_a[44] ^ io_b[44];
  wire _absDiff_T_90 = io_a[45] ^ io_b[45];
  wire _absDiff_T_92 = io_a[46] ^ io_b[46];
  wire _absDiff_T_94 = io_a[47] ^ io_b[47];
  wire _absDiff_T_96 = io_a[48] ^ io_b[48];
  wire _absDiff_T_98 = io_a[49] ^ io_b[49];
  wire _GEN_0 = ~(io_a[1]) & io_b[1] | ~_absDiff_T_2 & _GEN;
  wire _GEN_1 = ~_absDiff_T_2 & ~_absDiff_WIRE_0;
  wire _GEN_2 = ~(io_a[2]) & io_b[2] | ~_absDiff_T_4 & _GEN_0;
  wire _GEN_3 = ~_absDiff_T_4 & _GEN_1;
  wire _GEN_4 = ~(io_a[3]) & io_b[3] | ~_absDiff_T_6 & _GEN_2;
  wire _GEN_5 = ~_absDiff_T_6 & _GEN_3;
  wire _GEN_6 = ~(io_a[4]) & io_b[4] | ~_absDiff_T_8 & _GEN_4;
  wire _GEN_7 = ~_absDiff_T_8 & _GEN_5;
  wire _GEN_8 = ~(io_a[5]) & io_b[5] | ~_absDiff_T_10 & _GEN_6;
  wire _GEN_9 = ~_absDiff_T_10 & _GEN_7;
  wire _GEN_10 = ~(io_a[6]) & io_b[6] | ~_absDiff_T_12 & _GEN_8;
  wire _GEN_11 = ~_absDiff_T_12 & _GEN_9;
  wire _GEN_12 = ~(io_a[7]) & io_b[7] | ~_absDiff_T_14 & _GEN_10;
  wire _GEN_13 = ~_absDiff_T_14 & _GEN_11;
  wire _GEN_14 = ~(io_a[8]) & io_b[8] | ~_absDiff_T_16 & _GEN_12;
  wire _GEN_15 = ~_absDiff_T_16 & _GEN_13;
  wire _GEN_16 = ~(io_a[9]) & io_b[9] | ~_absDiff_T_18 & _GEN_14;
  wire _GEN_17 = ~_absDiff_T_18 & _GEN_15;
  wire _GEN_18 = ~(io_a[10]) & io_b[10] | ~_absDiff_T_20 & _GEN_16;
  wire _GEN_19 = ~_absDiff_T_20 & _GEN_17;
  wire _GEN_20 = ~(io_a[11]) & io_b[11] | ~_absDiff_T_22 & _GEN_18;
  wire _GEN_21 = ~_absDiff_T_22 & _GEN_19;
  wire _GEN_22 = ~(io_a[12]) & io_b[12] | ~_absDiff_T_24 & _GEN_20;
  wire _GEN_23 = ~_absDiff_T_24 & _GEN_21;
  wire _GEN_24 = ~(io_a[13]) & io_b[13] | ~_absDiff_T_26 & _GEN_22;
  wire _GEN_25 = ~_absDiff_T_26 & _GEN_23;
  wire _GEN_26 = ~(io_a[14]) & io_b[14] | ~_absDiff_T_28 & _GEN_24;
  wire _GEN_27 = ~_absDiff_T_28 & _GEN_25;
  wire _GEN_28 = ~(io_a[15]) & io_b[15] | ~_absDiff_T_30 & _GEN_26;
  wire _GEN_29 = ~_absDiff_T_30 & _GEN_27;
  wire _GEN_30 = ~(io_a[16]) & io_b[16] | ~_absDiff_T_32 & _GEN_28;
  wire _GEN_31 = ~_absDiff_T_32 & _GEN_29;
  wire _GEN_32 = ~(io_a[17]) & io_b[17] | ~_absDiff_T_34 & _GEN_30;
  wire _GEN_33 = ~_absDiff_T_34 & _GEN_31;
  wire _GEN_34 = ~(io_a[18]) & io_b[18] | ~_absDiff_T_36 & _GEN_32;
  wire _GEN_35 = ~_absDiff_T_36 & _GEN_33;
  wire _GEN_36 = ~(io_a[19]) & io_b[19] | ~_absDiff_T_38 & _GEN_34;
  wire _GEN_37 = ~_absDiff_T_38 & _GEN_35;
  wire _GEN_38 = ~(io_a[20]) & io_b[20] | ~_absDiff_T_40 & _GEN_36;
  wire _GEN_39 = ~_absDiff_T_40 & _GEN_37;
  wire _GEN_40 = ~(io_a[21]) & io_b[21] | ~_absDiff_T_42 & _GEN_38;
  wire _GEN_41 = ~_absDiff_T_42 & _GEN_39;
  wire _GEN_42 = ~(io_a[22]) & io_b[22] | ~_absDiff_T_44 & _GEN_40;
  wire _GEN_43 = ~_absDiff_T_44 & _GEN_41;
  wire _GEN_44 = ~(io_a[23]) & io_b[23] | ~_absDiff_T_46 & _GEN_42;
  wire _GEN_45 = ~_absDiff_T_46 & _GEN_43;
  wire _GEN_46 = ~(io_a[24]) & io_b[24] | ~_absDiff_T_48 & _GEN_44;
  wire _GEN_47 = ~_absDiff_T_48 & _GEN_45;
  wire _GEN_48 = ~(io_a[25]) & io_b[25] | ~_absDiff_T_50 & _GEN_46;
  wire _GEN_49 = ~_absDiff_T_50 & _GEN_47;
  wire _GEN_50 = ~(io_a[26]) & io_b[26] | ~_absDiff_T_52 & _GEN_48;
  wire _GEN_51 = ~_absDiff_T_52 & _GEN_49;
  wire _GEN_52 = ~(io_a[27]) & io_b[27] | ~_absDiff_T_54 & _GEN_50;
  wire _GEN_53 = ~_absDiff_T_54 & _GEN_51;
  wire _GEN_54 = ~(io_a[28]) & io_b[28] | ~_absDiff_T_56 & _GEN_52;
  wire _GEN_55 = ~_absDiff_T_56 & _GEN_53;
  wire _GEN_56 = ~(io_a[29]) & io_b[29] | ~_absDiff_T_58 & _GEN_54;
  wire _GEN_57 = ~_absDiff_T_58 & _GEN_55;
  wire _GEN_58 = ~(io_a[30]) & io_b[30] | ~_absDiff_T_60 & _GEN_56;
  wire _GEN_59 = ~_absDiff_T_60 & _GEN_57;
  wire _GEN_60 = ~(io_a[31]) & io_b[31] | ~_absDiff_T_62 & _GEN_58;
  wire _GEN_61 = ~_absDiff_T_62 & _GEN_59;
  wire _GEN_62 = ~(io_a[32]) & io_b[32] | ~_absDiff_T_64 & _GEN_60;
  wire _GEN_63 = ~_absDiff_T_64 & _GEN_61;
  wire _GEN_64 = ~(io_a[33]) & io_b[33] | ~_absDiff_T_66 & _GEN_62;
  wire _GEN_65 = ~_absDiff_T_66 & _GEN_63;
  wire _GEN_66 = ~(io_a[34]) & io_b[34] | ~_absDiff_T_68 & _GEN_64;
  wire _GEN_67 = ~_absDiff_T_68 & _GEN_65;
  wire _GEN_68 = ~(io_a[35]) & io_b[35] | ~_absDiff_T_70 & _GEN_66;
  wire _GEN_69 = ~_absDiff_T_70 & _GEN_67;
  wire _GEN_70 = ~(io_a[36]) & io_b[36] | ~_absDiff_T_72 & _GEN_68;
  wire _GEN_71 = ~_absDiff_T_72 & _GEN_69;
  wire _GEN_72 = ~(io_a[37]) & io_b[37] | ~_absDiff_T_74 & _GEN_70;
  wire _GEN_73 = ~_absDiff_T_74 & _GEN_71;
  wire _GEN_74 = ~(io_a[38]) & io_b[38] | ~_absDiff_T_76 & _GEN_72;
  wire _GEN_75 = ~_absDiff_T_76 & _GEN_73;
  wire _GEN_76 = ~(io_a[39]) & io_b[39] | ~_absDiff_T_78 & _GEN_74;
  wire _GEN_77 = ~_absDiff_T_78 & _GEN_75;
  wire _GEN_78 = ~(io_a[40]) & io_b[40] | ~_absDiff_T_80 & _GEN_76;
  wire _GEN_79 = ~_absDiff_T_80 & _GEN_77;
  wire _GEN_80 = ~(io_a[41]) & io_b[41] | ~_absDiff_T_82 & _GEN_78;
  wire _GEN_81 = ~_absDiff_T_82 & _GEN_79;
  wire _GEN_82 = ~(io_a[42]) & io_b[42] | ~_absDiff_T_84 & _GEN_80;
  wire _GEN_83 = ~_absDiff_T_84 & _GEN_81;
  wire _GEN_84 = ~(io_a[43]) & io_b[43] | ~_absDiff_T_86 & _GEN_82;
  wire _GEN_85 = ~_absDiff_T_86 & _GEN_83;
  wire _GEN_86 = ~(io_a[44]) & io_b[44] | ~_absDiff_T_88 & _GEN_84;
  wire _GEN_87 = ~_absDiff_T_88 & _GEN_85;
  wire _GEN_88 = ~(io_a[45]) & io_b[45] | ~_absDiff_T_90 & _GEN_86;
  wire _GEN_89 = ~_absDiff_T_90 & _GEN_87;
  wire _GEN_90 = ~(io_a[46]) & io_b[46] | ~_absDiff_T_92 & _GEN_88;
  wire _GEN_91 = ~_absDiff_T_92 & _GEN_89;
  wire _GEN_92 = ~(io_a[47]) & io_b[47] | ~_absDiff_T_94 & _GEN_90;
  wire _GEN_93 = ~_absDiff_T_94 & _GEN_91;
  wire _GEN_94 = ~(io_a[48]) & io_b[48] | ~_absDiff_T_96 & _GEN_92;
  wire lt = ~(io_a[49]) & io_b[49] | ~_absDiff_T_98 & _GEN_94;
  assign io_lt = lt;
  assign io_absDiff =
    {_absDiff_T_98 ^ _GEN_94 ^ lt & ~(~_absDiff_T_96 & _GEN_93),
     _absDiff_T_96 ^ _GEN_92 ^ lt & ~_GEN_93,
     _absDiff_T_94 ^ _GEN_90 ^ lt & ~_GEN_91,
     _absDiff_T_92 ^ _GEN_88 ^ lt & ~_GEN_89,
     _absDiff_T_90 ^ _GEN_86 ^ lt & ~_GEN_87,
     _absDiff_T_88 ^ _GEN_84 ^ lt & ~_GEN_85,
     _absDiff_T_86 ^ _GEN_82 ^ lt & ~_GEN_83,
     _absDiff_T_84 ^ _GEN_80 ^ lt & ~_GEN_81,
     _absDiff_T_82 ^ _GEN_78 ^ lt & ~_GEN_79,
     _absDiff_T_80 ^ _GEN_76 ^ lt & ~_GEN_77,
     _absDiff_T_78 ^ _GEN_74 ^ lt & ~_GEN_75,
     _absDiff_T_76 ^ _GEN_72 ^ lt & ~_GEN_73,
     _absDiff_T_74 ^ _GEN_70 ^ lt & ~_GEN_71,
     _absDiff_T_72 ^ _GEN_68 ^ lt & ~_GEN_69,
     _absDiff_T_70 ^ _GEN_66 ^ lt & ~_GEN_67,
     _absDiff_T_68 ^ _GEN_64 ^ lt & ~_GEN_65,
     _absDiff_T_66 ^ _GEN_62 ^ lt & ~_GEN_63,
     _absDiff_T_64 ^ _GEN_60 ^ lt & ~_GEN_61,
     _absDiff_T_62 ^ _GEN_58 ^ lt & ~_GEN_59,
     _absDiff_T_60 ^ _GEN_56 ^ lt & ~_GEN_57,
     _absDiff_T_58 ^ _GEN_54 ^ lt & ~_GEN_55,
     _absDiff_T_56 ^ _GEN_52 ^ lt & ~_GEN_53,
     _absDiff_T_54 ^ _GEN_50 ^ lt & ~_GEN_51,
     _absDiff_T_52 ^ _GEN_48 ^ lt & ~_GEN_49,
     _absDiff_T_50 ^ _GEN_46 ^ lt & ~_GEN_47,
     _absDiff_T_48 ^ _GEN_44 ^ lt & ~_GEN_45,
     _absDiff_T_46 ^ _GEN_42 ^ lt & ~_GEN_43,
     _absDiff_T_44 ^ _GEN_40 ^ lt & ~_GEN_41,
     _absDiff_T_42 ^ _GEN_38 ^ lt & ~_GEN_39,
     _absDiff_T_40 ^ _GEN_36 ^ lt & ~_GEN_37,
     _absDiff_T_38 ^ _GEN_34 ^ lt & ~_GEN_35,
     _absDiff_T_36 ^ _GEN_32 ^ lt & ~_GEN_33,
     _absDiff_T_34 ^ _GEN_30 ^ lt & ~_GEN_31,
     _absDiff_T_32 ^ _GEN_28 ^ lt & ~_GEN_29,
     _absDiff_T_30 ^ _GEN_26 ^ lt & ~_GEN_27,
     _absDiff_T_28 ^ _GEN_24 ^ lt & ~_GEN_25,
     _absDiff_T_26 ^ _GEN_22 ^ lt & ~_GEN_23,
     _absDiff_T_24 ^ _GEN_20 ^ lt & ~_GEN_21,
     _absDiff_T_22 ^ _GEN_18 ^ lt & ~_GEN_19,
     _absDiff_T_20 ^ _GEN_16 ^ lt & ~_GEN_17,
     _absDiff_T_18 ^ _GEN_14 ^ lt & ~_GEN_15,
     _absDiff_T_16 ^ _GEN_12 ^ lt & ~_GEN_13,
     _absDiff_T_14 ^ _GEN_10 ^ lt & ~_GEN_11,
     _absDiff_T_12 ^ _GEN_8 ^ lt & ~_GEN_9,
     _absDiff_T_10 ^ _GEN_6 ^ lt & ~_GEN_7,
     _absDiff_T_8 ^ _GEN_4 ^ lt & ~_GEN_5,
     _absDiff_T_6 ^ _GEN_2 ^ lt & ~_GEN_3,
     _absDiff_T_4 ^ _GEN_0 ^ lt & ~_GEN_1,
     _absDiff_T_2 ^ _GEN ^ lt & _absDiff_WIRE_0,
     _absDiff_WIRE_0};
endmodule

