// Generated by CIRCT firtool-1.138.0
module PrefixAdder(
  input  io_a,
         io_b,
         io_cin,
  output io_sum,
         io_cout
);

  wire _GEN = io_a ^ io_b;
  assign io_sum = _GEN ^ io_cin;
  assign io_cout = io_a & io_b | _GEN & io_cin;
endmodule

