// Generated by CIRCT firtool-1.138.0
module PrefixAdder(
  input  [14:0] io_a,
                io_b,
  input         io_cin,
  output [14:0] io_sum,
  output        io_cout
);

  wire _GEN = io_a[0] & io_b[0];
  wire _GEN_0 = io_a[0] ^ io_b[0];
  wire _GEN_1 = io_a[1] ^ io_b[1];
  wire _GEN_2 = io_a[2] ^ io_b[2];
  wire _GEN_3 = io_a[3] ^ io_b[3];
  wire _GEN_4 = io_a[4] ^ io_b[4];
  wire _GEN_5 = io_a[5] ^ io_b[5];
  wire _GEN_6 = io_a[6] ^ io_b[6];
  wire _GEN_7 = io_a[7] ^ io_b[7];
  wire _GEN_8 = io_a[8] ^ io_b[8];
  wire _GEN_9 = io_a[9] ^ io_b[9];
  wire _GEN_10 = io_a[10] ^ io_b[10];
  wire _GEN_11 = io_a[11] ^ io_b[11];
  wire _GEN_12 = io_a[12] ^ io_b[12];
  wire _GEN_13 = io_a[13] ^ io_b[13];
  wire _GEN_14 = io_a[14] ^ io_b[14];
  wire _GEN_15 = io_a[1] & io_b[1] | _GEN_1 & _GEN;
  wire _GEN_16 = _GEN_1 & _GEN_0;
  wire _GEN_17 = io_a[2] & io_b[2] | _GEN_2 & _GEN_15;
  wire _GEN_18 = _GEN_2 & _GEN_16;
  wire _GEN_19 = io_a[3] & io_b[3] | _GEN_3 & _GEN_17;
  wire _GEN_20 = _GEN_3 & _GEN_18;
  wire _GEN_21 = io_a[4] & io_b[4] | _GEN_4 & _GEN_19;
  wire _GEN_22 = _GEN_4 & _GEN_20;
  wire _GEN_23 = io_a[5] & io_b[5] | _GEN_5 & _GEN_21;
  wire _GEN_24 = _GEN_5 & _GEN_22;
  wire _GEN_25 = io_a[6] & io_b[6] | _GEN_6 & _GEN_23;
  wire _GEN_26 = _GEN_6 & _GEN_24;
  wire _GEN_27 = io_a[7] & io_b[7] | _GEN_7 & _GEN_25;
  wire _GEN_28 = _GEN_7 & _GEN_26;
  wire _GEN_29 = io_a[8] & io_b[8] | _GEN_8 & _GEN_27;
  wire _GEN_30 = _GEN_8 & _GEN_28;
  wire _GEN_31 = io_a[9] & io_b[9] | _GEN_9 & _GEN_29;
  wire _GEN_32 = _GEN_9 & _GEN_30;
  wire _GEN_33 = io_a[10] & io_b[10] | _GEN_10 & _GEN_31;
  wire _GEN_34 = _GEN_10 & _GEN_32;
  wire _GEN_35 = io_a[11] & io_b[11] | _GEN_11 & _GEN_33;
  wire _GEN_36 = _GEN_11 & _GEN_34;
  wire _GEN_37 = io_a[12] & io_b[12] | _GEN_12 & _GEN_35;
  wire _GEN_38 = _GEN_12 & _GEN_36;
  wire _GEN_39 = io_a[13] & io_b[13] | _GEN_13 & _GEN_37;
  wire _GEN_40 = _GEN_13 & _GEN_38;
  assign io_sum =
    {_GEN_14 ^ (_GEN_39 | _GEN_40 & io_cin),
     _GEN_13 ^ (_GEN_37 | _GEN_38 & io_cin),
     _GEN_12 ^ (_GEN_35 | _GEN_36 & io_cin),
     _GEN_11 ^ (_GEN_33 | _GEN_34 & io_cin),
     _GEN_10 ^ (_GEN_31 | _GEN_32 & io_cin),
     _GEN_9 ^ (_GEN_29 | _GEN_30 & io_cin),
     _GEN_8 ^ (_GEN_27 | _GEN_28 & io_cin),
     _GEN_7 ^ (_GEN_25 | _GEN_26 & io_cin),
     _GEN_6 ^ (_GEN_23 | _GEN_24 & io_cin),
     _GEN_5 ^ (_GEN_21 | _GEN_22 & io_cin),
     _GEN_4 ^ (_GEN_19 | _GEN_20 & io_cin),
     _GEN_3 ^ (_GEN_17 | _GEN_18 & io_cin),
     _GEN_2 ^ (_GEN_15 | _GEN_16 & io_cin),
     _GEN_1 ^ (_GEN | _GEN_0 & io_cin),
     _GEN_0 ^ io_cin};
  assign io_cout = io_a[14] & io_b[14] | _GEN_14 & _GEN_39 | _GEN_14 & _GEN_40 & io_cin;
endmodule

