// Generated by CIRCT firtool-1.138.0
module PrefixAdder(
  input  [23:0] io_a,
                io_b,
  input         io_cin,
  output [23:0] io_sum,
  output        io_cout
);

  wire _GEN = io_a[0] & io_b[0];
  wire _GEN_0 = io_a[0] ^ io_b[0];
  wire _GEN_1 = io_a[1] ^ io_b[1];
  wire _GEN_2 = io_a[2] ^ io_b[2];
  wire _GEN_3 = io_a[3] ^ io_b[3];
  wire _GEN_4 = io_a[4] ^ io_b[4];
  wire _GEN_5 = io_a[5] ^ io_b[5];
  wire _GEN_6 = io_a[6] ^ io_b[6];
  wire _GEN_7 = io_a[7] ^ io_b[7];
  wire _GEN_8 = io_a[8] ^ io_b[8];
  wire _GEN_9 = io_a[9] ^ io_b[9];
  wire _GEN_10 = io_a[10] ^ io_b[10];
  wire _GEN_11 = io_a[11] ^ io_b[11];
  wire _GEN_12 = io_a[12] ^ io_b[12];
  wire _GEN_13 = io_a[13] ^ io_b[13];
  wire _GEN_14 = io_a[14] ^ io_b[14];
  wire _GEN_15 = io_a[15] ^ io_b[15];
  wire _GEN_16 = io_a[16] ^ io_b[16];
  wire _GEN_17 = io_a[17] ^ io_b[17];
  wire _GEN_18 = io_a[18] ^ io_b[18];
  wire _GEN_19 = io_a[19] ^ io_b[19];
  wire _GEN_20 = io_a[20] ^ io_b[20];
  wire _GEN_21 = io_a[21] ^ io_b[21];
  wire _GEN_22 = io_a[22] ^ io_b[22];
  wire _GEN_23 = io_a[23] ^ io_b[23];
  wire _GEN_24 = io_a[1] & io_b[1] | _GEN_1 & _GEN;
  wire _GEN_25 = _GEN_1 & _GEN_0;
  wire _GEN_26 = io_a[2] & io_b[2] | _GEN_2 & _GEN_24;
  wire _GEN_27 = _GEN_2 & _GEN_25;
  wire _GEN_28 = io_a[3] & io_b[3] | _GEN_3 & _GEN_26;
  wire _GEN_29 = _GEN_3 & _GEN_27;
  wire _GEN_30 = io_a[4] & io_b[4] | _GEN_4 & _GEN_28;
  wire _GEN_31 = _GEN_4 & _GEN_29;
  wire _GEN_32 = io_a[5] & io_b[5] | _GEN_5 & _GEN_30;
  wire _GEN_33 = _GEN_5 & _GEN_31;
  wire _GEN_34 = io_a[6] & io_b[6] | _GEN_6 & _GEN_32;
  wire _GEN_35 = _GEN_6 & _GEN_33;
  wire _GEN_36 = io_a[7] & io_b[7] | _GEN_7 & _GEN_34;
  wire _GEN_37 = _GEN_7 & _GEN_35;
  wire _GEN_38 = io_a[8] & io_b[8] | _GEN_8 & _GEN_36;
  wire _GEN_39 = _GEN_8 & _GEN_37;
  wire _GEN_40 = io_a[9] & io_b[9] | _GEN_9 & _GEN_38;
  wire _GEN_41 = _GEN_9 & _GEN_39;
  wire _GEN_42 = io_a[10] & io_b[10] | _GEN_10 & _GEN_40;
  wire _GEN_43 = _GEN_10 & _GEN_41;
  wire _GEN_44 = io_a[11] & io_b[11] | _GEN_11 & _GEN_42;
  wire _GEN_45 = _GEN_11 & _GEN_43;
  wire _GEN_46 = io_a[12] & io_b[12] | _GEN_12 & _GEN_44;
  wire _GEN_47 = _GEN_12 & _GEN_45;
  wire _GEN_48 = io_a[13] & io_b[13] | _GEN_13 & _GEN_46;
  wire _GEN_49 = _GEN_13 & _GEN_47;
  wire _GEN_50 = io_a[14] & io_b[14] | _GEN_14 & _GEN_48;
  wire _GEN_51 = _GEN_14 & _GEN_49;
  wire _GEN_52 = io_a[15] & io_b[15] | _GEN_15 & _GEN_50;
  wire _GEN_53 = _GEN_15 & _GEN_51;
  wire _GEN_54 = io_a[16] & io_b[16] | _GEN_16 & _GEN_52;
  wire _GEN_55 = _GEN_16 & _GEN_53;
  wire _GEN_56 = io_a[17] & io_b[17] | _GEN_17 & _GEN_54;
  wire _GEN_57 = _GEN_17 & _GEN_55;
  wire _GEN_58 = io_a[18] & io_b[18] | _GEN_18 & _GEN_56;
  wire _GEN_59 = _GEN_18 & _GEN_57;
  wire _GEN_60 = io_a[19] & io_b[19] | _GEN_19 & _GEN_58;
  wire _GEN_61 = _GEN_19 & _GEN_59;
  wire _GEN_62 = io_a[20] & io_b[20] | _GEN_20 & _GEN_60;
  wire _GEN_63 = _GEN_20 & _GEN_61;
  wire _GEN_64 = io_a[21] & io_b[21] | _GEN_21 & _GEN_62;
  wire _GEN_65 = _GEN_21 & _GEN_63;
  wire _GEN_66 = io_a[22] & io_b[22] | _GEN_22 & _GEN_64;
  wire _GEN_67 = _GEN_22 & _GEN_65;
  assign io_sum =
    {_GEN_23 ^ (_GEN_66 | _GEN_67 & io_cin),
     _GEN_22 ^ (_GEN_64 | _GEN_65 & io_cin),
     _GEN_21 ^ (_GEN_62 | _GEN_63 & io_cin),
     _GEN_20 ^ (_GEN_60 | _GEN_61 & io_cin),
     _GEN_19 ^ (_GEN_58 | _GEN_59 & io_cin),
     _GEN_18 ^ (_GEN_56 | _GEN_57 & io_cin),
     _GEN_17 ^ (_GEN_54 | _GEN_55 & io_cin),
     _GEN_16 ^ (_GEN_52 | _GEN_53 & io_cin),
     _GEN_15 ^ (_GEN_50 | _GEN_51 & io_cin),
     _GEN_14 ^ (_GEN_48 | _GEN_49 & io_cin),
     _GEN_13 ^ (_GEN_46 | _GEN_47 & io_cin),
     _GEN_12 ^ (_GEN_44 | _GEN_45 & io_cin),
     _GEN_11 ^ (_GEN_42 | _GEN_43 & io_cin),
     _GEN_10 ^ (_GEN_40 | _GEN_41 & io_cin),
     _GEN_9 ^ (_GEN_38 | _GEN_39 & io_cin),
     _GEN_8 ^ (_GEN_36 | _GEN_37 & io_cin),
     _GEN_7 ^ (_GEN_34 | _GEN_35 & io_cin),
     _GEN_6 ^ (_GEN_32 | _GEN_33 & io_cin),
     _GEN_5 ^ (_GEN_30 | _GEN_31 & io_cin),
     _GEN_4 ^ (_GEN_28 | _GEN_29 & io_cin),
     _GEN_3 ^ (_GEN_26 | _GEN_27 & io_cin),
     _GEN_2 ^ (_GEN_24 | _GEN_25 & io_cin),
     _GEN_1 ^ (_GEN | _GEN_0 & io_cin),
     _GEN_0 ^ io_cin};
  assign io_cout = io_a[23] & io_b[23] | _GEN_23 & _GEN_66 | _GEN_23 & _GEN_67 & io_cin;
endmodule

