// Generated by CIRCT firtool-1.138.0
module PrefixAdder(
  input  [55:0] io_a,
                io_b,
  input         io_cin,
  output [55:0] io_sum,
  output        io_cout
);

  wire _GEN = io_a[0] & io_b[0];
  wire _GEN_0 = io_a[0] ^ io_b[0];
  wire _GEN_1 = io_a[1] ^ io_b[1];
  wire _GEN_2 = io_a[2] ^ io_b[2];
  wire _GEN_3 = io_a[3] ^ io_b[3];
  wire _GEN_4 = io_a[4] ^ io_b[4];
  wire _GEN_5 = io_a[5] ^ io_b[5];
  wire _GEN_6 = io_a[6] ^ io_b[6];
  wire _GEN_7 = io_a[7] ^ io_b[7];
  wire _GEN_8 = io_a[8] ^ io_b[8];
  wire _GEN_9 = io_a[9] ^ io_b[9];
  wire _GEN_10 = io_a[10] ^ io_b[10];
  wire _GEN_11 = io_a[11] ^ io_b[11];
  wire _GEN_12 = io_a[12] ^ io_b[12];
  wire _GEN_13 = io_a[13] ^ io_b[13];
  wire _GEN_14 = io_a[14] ^ io_b[14];
  wire _GEN_15 = io_a[15] ^ io_b[15];
  wire _GEN_16 = io_a[16] ^ io_b[16];
  wire _GEN_17 = io_a[17] ^ io_b[17];
  wire _GEN_18 = io_a[18] ^ io_b[18];
  wire _GEN_19 = io_a[19] ^ io_b[19];
  wire _GEN_20 = io_a[20] ^ io_b[20];
  wire _GEN_21 = io_a[21] ^ io_b[21];
  wire _GEN_22 = io_a[22] ^ io_b[22];
  wire _GEN_23 = io_a[23] ^ io_b[23];
  wire _GEN_24 = io_a[24] ^ io_b[24];
  wire _GEN_25 = io_a[25] ^ io_b[25];
  wire _GEN_26 = io_a[26] ^ io_b[26];
  wire _GEN_27 = io_a[27] ^ io_b[27];
  wire _GEN_28 = io_a[28] ^ io_b[28];
  wire _GEN_29 = io_a[29] ^ io_b[29];
  wire _GEN_30 = io_a[30] ^ io_b[30];
  wire _GEN_31 = io_a[31] ^ io_b[31];
  wire _GEN_32 = io_a[32] ^ io_b[32];
  wire _GEN_33 = io_a[33] ^ io_b[33];
  wire _GEN_34 = io_a[34] ^ io_b[34];
  wire _GEN_35 = io_a[35] ^ io_b[35];
  wire _GEN_36 = io_a[36] ^ io_b[36];
  wire _GEN_37 = io_a[37] ^ io_b[37];
  wire _GEN_38 = io_a[38] ^ io_b[38];
  wire _GEN_39 = io_a[39] ^ io_b[39];
  wire _GEN_40 = io_a[40] ^ io_b[40];
  wire _GEN_41 = io_a[41] ^ io_b[41];
  wire _GEN_42 = io_a[42] ^ io_b[42];
  wire _GEN_43 = io_a[43] ^ io_b[43];
  wire _GEN_44 = io_a[44] ^ io_b[44];
  wire _GEN_45 = io_a[45] ^ io_b[45];
  wire _GEN_46 = io_a[46] ^ io_b[46];
  wire _GEN_47 = io_a[47] ^ io_b[47];
  wire _GEN_48 = io_a[48] ^ io_b[48];
  wire _GEN_49 = io_a[49] ^ io_b[49];
  wire _GEN_50 = io_a[50] ^ io_b[50];
  wire _GEN_51 = io_a[51] ^ io_b[51];
  wire _GEN_52 = io_a[52] ^ io_b[52];
  wire _GEN_53 = io_a[53] ^ io_b[53];
  wire _GEN_54 = io_a[54] ^ io_b[54];
  wire _GEN_55 = io_a[55] ^ io_b[55];
  wire _GEN_56 = io_a[1] & io_b[1] | _GEN_1 & _GEN;
  wire _GEN_57 = _GEN_1 & _GEN_0;
  wire _GEN_58 = io_a[2] & io_b[2] | _GEN_2 & _GEN_56;
  wire _GEN_59 = _GEN_2 & _GEN_57;
  wire _GEN_60 = io_a[3] & io_b[3] | _GEN_3 & _GEN_58;
  wire _GEN_61 = _GEN_3 & _GEN_59;
  wire _GEN_62 = io_a[4] & io_b[4] | _GEN_4 & _GEN_60;
  wire _GEN_63 = _GEN_4 & _GEN_61;
  wire _GEN_64 = io_a[5] & io_b[5] | _GEN_5 & _GEN_62;
  wire _GEN_65 = _GEN_5 & _GEN_63;
  wire _GEN_66 = io_a[6] & io_b[6] | _GEN_6 & _GEN_64;
  wire _GEN_67 = _GEN_6 & _GEN_65;
  wire _GEN_68 = io_a[7] & io_b[7] | _GEN_7 & _GEN_66;
  wire _GEN_69 = _GEN_7 & _GEN_67;
  wire _GEN_70 = io_a[8] & io_b[8] | _GEN_8 & _GEN_68;
  wire _GEN_71 = _GEN_8 & _GEN_69;
  wire _GEN_72 = io_a[9] & io_b[9] | _GEN_9 & _GEN_70;
  wire _GEN_73 = _GEN_9 & _GEN_71;
  wire _GEN_74 = io_a[10] & io_b[10] | _GEN_10 & _GEN_72;
  wire _GEN_75 = _GEN_10 & _GEN_73;
  wire _GEN_76 = io_a[11] & io_b[11] | _GEN_11 & _GEN_74;
  wire _GEN_77 = _GEN_11 & _GEN_75;
  wire _GEN_78 = io_a[12] & io_b[12] | _GEN_12 & _GEN_76;
  wire _GEN_79 = _GEN_12 & _GEN_77;
  wire _GEN_80 = io_a[13] & io_b[13] | _GEN_13 & _GEN_78;
  wire _GEN_81 = _GEN_13 & _GEN_79;
  wire _GEN_82 = io_a[14] & io_b[14] | _GEN_14 & _GEN_80;
  wire _GEN_83 = _GEN_14 & _GEN_81;
  wire _GEN_84 = io_a[15] & io_b[15] | _GEN_15 & _GEN_82;
  wire _GEN_85 = _GEN_15 & _GEN_83;
  wire _GEN_86 = io_a[16] & io_b[16] | _GEN_16 & _GEN_84;
  wire _GEN_87 = _GEN_16 & _GEN_85;
  wire _GEN_88 = io_a[17] & io_b[17] | _GEN_17 & _GEN_86;
  wire _GEN_89 = _GEN_17 & _GEN_87;
  wire _GEN_90 = io_a[18] & io_b[18] | _GEN_18 & _GEN_88;
  wire _GEN_91 = _GEN_18 & _GEN_89;
  wire _GEN_92 = io_a[19] & io_b[19] | _GEN_19 & _GEN_90;
  wire _GEN_93 = _GEN_19 & _GEN_91;
  wire _GEN_94 = io_a[20] & io_b[20] | _GEN_20 & _GEN_92;
  wire _GEN_95 = _GEN_20 & _GEN_93;
  wire _GEN_96 = io_a[21] & io_b[21] | _GEN_21 & _GEN_94;
  wire _GEN_97 = _GEN_21 & _GEN_95;
  wire _GEN_98 = io_a[22] & io_b[22] | _GEN_22 & _GEN_96;
  wire _GEN_99 = _GEN_22 & _GEN_97;
  wire _GEN_100 = io_a[23] & io_b[23] | _GEN_23 & _GEN_98;
  wire _GEN_101 = _GEN_23 & _GEN_99;
  wire _GEN_102 = io_a[24] & io_b[24] | _GEN_24 & _GEN_100;
  wire _GEN_103 = _GEN_24 & _GEN_101;
  wire _GEN_104 = io_a[25] & io_b[25] | _GEN_25 & _GEN_102;
  wire _GEN_105 = _GEN_25 & _GEN_103;
  wire _GEN_106 = io_a[26] & io_b[26] | _GEN_26 & _GEN_104;
  wire _GEN_107 = _GEN_26 & _GEN_105;
  wire _GEN_108 = io_a[27] & io_b[27] | _GEN_27 & _GEN_106;
  wire _GEN_109 = _GEN_27 & _GEN_107;
  wire _GEN_110 = io_a[28] & io_b[28] | _GEN_28 & _GEN_108;
  wire _GEN_111 = _GEN_28 & _GEN_109;
  wire _GEN_112 = io_a[29] & io_b[29] | _GEN_29 & _GEN_110;
  wire _GEN_113 = _GEN_29 & _GEN_111;
  wire _GEN_114 = io_a[30] & io_b[30] | _GEN_30 & _GEN_112;
  wire _GEN_115 = _GEN_30 & _GEN_113;
  wire _GEN_116 = io_a[31] & io_b[31] | _GEN_31 & _GEN_114;
  wire _GEN_117 = _GEN_31 & _GEN_115;
  wire _GEN_118 = io_a[32] & io_b[32] | _GEN_32 & _GEN_116;
  wire _GEN_119 = _GEN_32 & _GEN_117;
  wire _GEN_120 = io_a[33] & io_b[33] | _GEN_33 & _GEN_118;
  wire _GEN_121 = _GEN_33 & _GEN_119;
  wire _GEN_122 = io_a[34] & io_b[34] | _GEN_34 & _GEN_120;
  wire _GEN_123 = _GEN_34 & _GEN_121;
  wire _GEN_124 = io_a[35] & io_b[35] | _GEN_35 & _GEN_122;
  wire _GEN_125 = _GEN_35 & _GEN_123;
  wire _GEN_126 = io_a[36] & io_b[36] | _GEN_36 & _GEN_124;
  wire _GEN_127 = _GEN_36 & _GEN_125;
  wire _GEN_128 = io_a[37] & io_b[37] | _GEN_37 & _GEN_126;
  wire _GEN_129 = _GEN_37 & _GEN_127;
  wire _GEN_130 = io_a[38] & io_b[38] | _GEN_38 & _GEN_128;
  wire _GEN_131 = _GEN_38 & _GEN_129;
  wire _GEN_132 = io_a[39] & io_b[39] | _GEN_39 & _GEN_130;
  wire _GEN_133 = _GEN_39 & _GEN_131;
  wire _GEN_134 = io_a[40] & io_b[40] | _GEN_40 & _GEN_132;
  wire _GEN_135 = _GEN_40 & _GEN_133;
  wire _GEN_136 = io_a[41] & io_b[41] | _GEN_41 & _GEN_134;
  wire _GEN_137 = _GEN_41 & _GEN_135;
  wire _GEN_138 = io_a[42] & io_b[42] | _GEN_42 & _GEN_136;
  wire _GEN_139 = _GEN_42 & _GEN_137;
  wire _GEN_140 = io_a[43] & io_b[43] | _GEN_43 & _GEN_138;
  wire _GEN_141 = _GEN_43 & _GEN_139;
  wire _GEN_142 = io_a[44] & io_b[44] | _GEN_44 & _GEN_140;
  wire _GEN_143 = _GEN_44 & _GEN_141;
  wire _GEN_144 = io_a[45] & io_b[45] | _GEN_45 & _GEN_142;
  wire _GEN_145 = _GEN_45 & _GEN_143;
  wire _GEN_146 = io_a[46] & io_b[46] | _GEN_46 & _GEN_144;
  wire _GEN_147 = _GEN_46 & _GEN_145;
  wire _GEN_148 = io_a[47] & io_b[47] | _GEN_47 & _GEN_146;
  wire _GEN_149 = _GEN_47 & _GEN_147;
  wire _GEN_150 = io_a[48] & io_b[48] | _GEN_48 & _GEN_148;
  wire _GEN_151 = _GEN_48 & _GEN_149;
  wire _GEN_152 = io_a[49] & io_b[49] | _GEN_49 & _GEN_150;
  wire _GEN_153 = _GEN_49 & _GEN_151;
  wire _GEN_154 = io_a[50] & io_b[50] | _GEN_50 & _GEN_152;
  wire _GEN_155 = _GEN_50 & _GEN_153;
  wire _GEN_156 = io_a[51] & io_b[51] | _GEN_51 & _GEN_154;
  wire _GEN_157 = _GEN_51 & _GEN_155;
  wire _GEN_158 = io_a[52] & io_b[52] | _GEN_52 & _GEN_156;
  wire _GEN_159 = _GEN_52 & _GEN_157;
  wire _GEN_160 = io_a[53] & io_b[53] | _GEN_53 & _GEN_158;
  wire _GEN_161 = _GEN_53 & _GEN_159;
  wire _GEN_162 = io_a[54] & io_b[54] | _GEN_54 & _GEN_160;
  wire _GEN_163 = _GEN_54 & _GEN_161;
  assign io_sum =
    {_GEN_55 ^ (_GEN_162 | _GEN_163 & io_cin),
     _GEN_54 ^ (_GEN_160 | _GEN_161 & io_cin),
     _GEN_53 ^ (_GEN_158 | _GEN_159 & io_cin),
     _GEN_52 ^ (_GEN_156 | _GEN_157 & io_cin),
     _GEN_51 ^ (_GEN_154 | _GEN_155 & io_cin),
     _GEN_50 ^ (_GEN_152 | _GEN_153 & io_cin),
     _GEN_49 ^ (_GEN_150 | _GEN_151 & io_cin),
     _GEN_48 ^ (_GEN_148 | _GEN_149 & io_cin),
     _GEN_47 ^ (_GEN_146 | _GEN_147 & io_cin),
     _GEN_46 ^ (_GEN_144 | _GEN_145 & io_cin),
     _GEN_45 ^ (_GEN_142 | _GEN_143 & io_cin),
     _GEN_44 ^ (_GEN_140 | _GEN_141 & io_cin),
     _GEN_43 ^ (_GEN_138 | _GEN_139 & io_cin),
     _GEN_42 ^ (_GEN_136 | _GEN_137 & io_cin),
     _GEN_41 ^ (_GEN_134 | _GEN_135 & io_cin),
     _GEN_40 ^ (_GEN_132 | _GEN_133 & io_cin),
     _GEN_39 ^ (_GEN_130 | _GEN_131 & io_cin),
     _GEN_38 ^ (_GEN_128 | _GEN_129 & io_cin),
     _GEN_37 ^ (_GEN_126 | _GEN_127 & io_cin),
     _GEN_36 ^ (_GEN_124 | _GEN_125 & io_cin),
     _GEN_35 ^ (_GEN_122 | _GEN_123 & io_cin),
     _GEN_34 ^ (_GEN_120 | _GEN_121 & io_cin),
     _GEN_33 ^ (_GEN_118 | _GEN_119 & io_cin),
     _GEN_32 ^ (_GEN_116 | _GEN_117 & io_cin),
     _GEN_31 ^ (_GEN_114 | _GEN_115 & io_cin),
     _GEN_30 ^ (_GEN_112 | _GEN_113 & io_cin),
     _GEN_29 ^ (_GEN_110 | _GEN_111 & io_cin),
     _GEN_28 ^ (_GEN_108 | _GEN_109 & io_cin),
     _GEN_27 ^ (_GEN_106 | _GEN_107 & io_cin),
     _GEN_26 ^ (_GEN_104 | _GEN_105 & io_cin),
     _GEN_25 ^ (_GEN_102 | _GEN_103 & io_cin),
     _GEN_24 ^ (_GEN_100 | _GEN_101 & io_cin),
     _GEN_23 ^ (_GEN_98 | _GEN_99 & io_cin),
     _GEN_22 ^ (_GEN_96 | _GEN_97 & io_cin),
     _GEN_21 ^ (_GEN_94 | _GEN_95 & io_cin),
     _GEN_20 ^ (_GEN_92 | _GEN_93 & io_cin),
     _GEN_19 ^ (_GEN_90 | _GEN_91 & io_cin),
     _GEN_18 ^ (_GEN_88 | _GEN_89 & io_cin),
     _GEN_17 ^ (_GEN_86 | _GEN_87 & io_cin),
     _GEN_16 ^ (_GEN_84 | _GEN_85 & io_cin),
     _GEN_15 ^ (_GEN_82 | _GEN_83 & io_cin),
     _GEN_14 ^ (_GEN_80 | _GEN_81 & io_cin),
     _GEN_13 ^ (_GEN_78 | _GEN_79 & io_cin),
     _GEN_12 ^ (_GEN_76 | _GEN_77 & io_cin),
     _GEN_11 ^ (_GEN_74 | _GEN_75 & io_cin),
     _GEN_10 ^ (_GEN_72 | _GEN_73 & io_cin),
     _GEN_9 ^ (_GEN_70 | _GEN_71 & io_cin),
     _GEN_8 ^ (_GEN_68 | _GEN_69 & io_cin),
     _GEN_7 ^ (_GEN_66 | _GEN_67 & io_cin),
     _GEN_6 ^ (_GEN_64 | _GEN_65 & io_cin),
     _GEN_5 ^ (_GEN_62 | _GEN_63 & io_cin),
     _GEN_4 ^ (_GEN_60 | _GEN_61 & io_cin),
     _GEN_3 ^ (_GEN_58 | _GEN_59 & io_cin),
     _GEN_2 ^ (_GEN_56 | _GEN_57 & io_cin),
     _GEN_1 ^ (_GEN | _GEN_0 & io_cin),
     _GEN_0 ^ io_cin};
  assign io_cout = io_a[55] & io_b[55] | _GEN_55 & _GEN_162 | _GEN_55 & _GEN_163 & io_cin;
endmodule

