// Generated by CIRCT firtool-1.138.0
module PrefixAbsDiff(
  input  [20:0] io_a,
                io_b,
  output        io_lt,
  output [20:0] io_absDiff
);

  wire _GEN = ~(io_a[0]) & io_b[0];
  wire _absDiff_WIRE_0 = io_a[0] ^ io_b[0];
  wire _absDiff_T_2 = io_a[1] ^ io_b[1];
  wire _absDiff_T_4 = io_a[2] ^ io_b[2];
  wire _absDiff_T_6 = io_a[3] ^ io_b[3];
  wire _absDiff_T_8 = io_a[4] ^ io_b[4];
  wire _absDiff_T_10 = io_a[5] ^ io_b[5];
  wire _absDiff_T_12 = io_a[6] ^ io_b[6];
  wire _absDiff_T_14 = io_a[7] ^ io_b[7];
  wire _absDiff_T_16 = io_a[8] ^ io_b[8];
  wire _absDiff_T_18 = io_a[9] ^ io_b[9];
  wire _absDiff_T_20 = io_a[10] ^ io_b[10];
  wire _absDiff_T_22 = io_a[11] ^ io_b[11];
  wire _absDiff_T_24 = io_a[12] ^ io_b[12];
  wire _absDiff_T_26 = io_a[13] ^ io_b[13];
  wire _absDiff_T_28 = io_a[14] ^ io_b[14];
  wire _absDiff_T_30 = io_a[15] ^ io_b[15];
  wire _absDiff_T_32 = io_a[16] ^ io_b[16];
  wire _absDiff_T_34 = io_a[17] ^ io_b[17];
  wire _absDiff_T_36 = io_a[18] ^ io_b[18];
  wire _absDiff_T_38 = io_a[19] ^ io_b[19];
  wire _absDiff_T_40 = io_a[20] ^ io_b[20];
  wire _GEN_0 = ~(io_a[1]) & io_b[1] | ~_absDiff_T_2 & _GEN;
  wire _GEN_1 = ~_absDiff_T_2 & ~_absDiff_WIRE_0;
  wire _GEN_2 = ~(io_a[2]) & io_b[2] | ~_absDiff_T_4 & _GEN_0;
  wire _GEN_3 = ~_absDiff_T_4 & _GEN_1;
  wire _GEN_4 = ~(io_a[3]) & io_b[3] | ~_absDiff_T_6 & _GEN_2;
  wire _GEN_5 = ~_absDiff_T_6 & _GEN_3;
  wire _GEN_6 = ~(io_a[4]) & io_b[4] | ~_absDiff_T_8 & _GEN_4;
  wire _GEN_7 = ~_absDiff_T_8 & _GEN_5;
  wire _GEN_8 = ~(io_a[5]) & io_b[5] | ~_absDiff_T_10 & _GEN_6;
  wire _GEN_9 = ~_absDiff_T_10 & _GEN_7;
  wire _GEN_10 = ~(io_a[6]) & io_b[6] | ~_absDiff_T_12 & _GEN_8;
  wire _GEN_11 = ~_absDiff_T_12 & _GEN_9;
  wire _GEN_12 = ~(io_a[7]) & io_b[7] | ~_absDiff_T_14 & _GEN_10;
  wire _GEN_13 = ~_absDiff_T_14 & _GEN_11;
  wire _GEN_14 = ~(io_a[8]) & io_b[8] | ~_absDiff_T_16 & _GEN_12;
  wire _GEN_15 = ~_absDiff_T_16 & _GEN_13;
  wire _GEN_16 = ~(io_a[9]) & io_b[9] | ~_absDiff_T_18 & _GEN_14;
  wire _GEN_17 = ~_absDiff_T_18 & _GEN_15;
  wire _GEN_18 = ~(io_a[10]) & io_b[10] | ~_absDiff_T_20 & _GEN_16;
  wire _GEN_19 = ~_absDiff_T_20 & _GEN_17;
  wire _GEN_20 = ~(io_a[11]) & io_b[11] | ~_absDiff_T_22 & _GEN_18;
  wire _GEN_21 = ~_absDiff_T_22 & _GEN_19;
  wire _GEN_22 = ~(io_a[12]) & io_b[12] | ~_absDiff_T_24 & _GEN_20;
  wire _GEN_23 = ~_absDiff_T_24 & _GEN_21;
  wire _GEN_24 = ~(io_a[13]) & io_b[13] | ~_absDiff_T_26 & _GEN_22;
  wire _GEN_25 = ~_absDiff_T_26 & _GEN_23;
  wire _GEN_26 = ~(io_a[14]) & io_b[14] | ~_absDiff_T_28 & _GEN_24;
  wire _GEN_27 = ~_absDiff_T_28 & _GEN_25;
  wire _GEN_28 = ~(io_a[15]) & io_b[15] | ~_absDiff_T_30 & _GEN_26;
  wire _GEN_29 = ~_absDiff_T_30 & _GEN_27;
  wire _GEN_30 = ~(io_a[16]) & io_b[16] | ~_absDiff_T_32 & _GEN_28;
  wire _GEN_31 = ~_absDiff_T_32 & _GEN_29;
  wire _GEN_32 = ~(io_a[17]) & io_b[17] | ~_absDiff_T_34 & _GEN_30;
  wire _GEN_33 = ~_absDiff_T_34 & _GEN_31;
  wire _GEN_34 = ~(io_a[18]) & io_b[18] | ~_absDiff_T_36 & _GEN_32;
  wire _GEN_35 = ~_absDiff_T_36 & _GEN_33;
  wire _GEN_36 = ~(io_a[19]) & io_b[19] | ~_absDiff_T_38 & _GEN_34;
  wire lt = ~(io_a[20]) & io_b[20] | ~_absDiff_T_40 & _GEN_36;
  assign io_lt = lt;
  assign io_absDiff =
    {_absDiff_T_40 ^ _GEN_36 ^ lt & ~(~_absDiff_T_38 & _GEN_35),
     _absDiff_T_38 ^ _GEN_34 ^ lt & ~_GEN_35,
     _absDiff_T_36 ^ _GEN_32 ^ lt & ~_GEN_33,
     _absDiff_T_34 ^ _GEN_30 ^ lt & ~_GEN_31,
     _absDiff_T_32 ^ _GEN_28 ^ lt & ~_GEN_29,
     _absDiff_T_30 ^ _GEN_26 ^ lt & ~_GEN_27,
     _absDiff_T_28 ^ _GEN_24 ^ lt & ~_GEN_25,
     _absDiff_T_26 ^ _GEN_22 ^ lt & ~_GEN_23,
     _absDiff_T_24 ^ _GEN_20 ^ lt & ~_GEN_21,
     _absDiff_T_22 ^ _GEN_18 ^ lt & ~_GEN_19,
     _absDiff_T_20 ^ _GEN_16 ^ lt & ~_GEN_17,
     _absDiff_T_18 ^ _GEN_14 ^ lt & ~_GEN_15,
     _absDiff_T_16 ^ _GEN_12 ^ lt & ~_GEN_13,
     _absDiff_T_14 ^ _GEN_10 ^ lt & ~_GEN_11,
     _absDiff_T_12 ^ _GEN_8 ^ lt & ~_GEN_9,
     _absDiff_T_10 ^ _GEN_6 ^ lt & ~_GEN_7,
     _absDiff_T_8 ^ _GEN_4 ^ lt & ~_GEN_5,
     _absDiff_T_6 ^ _GEN_2 ^ lt & ~_GEN_3,
     _absDiff_T_4 ^ _GEN_0 ^ lt & ~_GEN_1,
     _absDiff_T_2 ^ _GEN ^ lt & _absDiff_WIRE_0,
     _absDiff_WIRE_0};
endmodule

