// Generated by CIRCT firtool-1.138.0
module PrefixAbsDiff(
  input  [104:0] io_a,
                 io_b,
  output         io_lt,
  output [104:0] io_absDiff
);

  wire _GEN = ~(io_a[0]) & io_b[0];
  wire _absDiff_WIRE_0 = io_a[0] ^ io_b[0];
  wire _absDiff_T_2 = io_a[1] ^ io_b[1];
  wire _absDiff_T_4 = io_a[2] ^ io_b[2];
  wire _absDiff_T_6 = io_a[3] ^ io_b[3];
  wire _absDiff_T_8 = io_a[4] ^ io_b[4];
  wire _absDiff_T_10 = io_a[5] ^ io_b[5];
  wire _absDiff_T_12 = io_a[6] ^ io_b[6];
  wire _absDiff_T_14 = io_a[7] ^ io_b[7];
  wire _absDiff_T_16 = io_a[8] ^ io_b[8];
  wire _absDiff_T_18 = io_a[9] ^ io_b[9];
  wire _absDiff_T_20 = io_a[10] ^ io_b[10];
  wire _absDiff_T_22 = io_a[11] ^ io_b[11];
  wire _absDiff_T_24 = io_a[12] ^ io_b[12];
  wire _absDiff_T_26 = io_a[13] ^ io_b[13];
  wire _absDiff_T_28 = io_a[14] ^ io_b[14];
  wire _absDiff_T_30 = io_a[15] ^ io_b[15];
  wire _absDiff_T_32 = io_a[16] ^ io_b[16];
  wire _absDiff_T_34 = io_a[17] ^ io_b[17];
  wire _absDiff_T_36 = io_a[18] ^ io_b[18];
  wire _absDiff_T_38 = io_a[19] ^ io_b[19];
  wire _absDiff_T_40 = io_a[20] ^ io_b[20];
  wire _absDiff_T_42 = io_a[21] ^ io_b[21];
  wire _absDiff_T_44 = io_a[22] ^ io_b[22];
  wire _absDiff_T_46 = io_a[23] ^ io_b[23];
  wire _absDiff_T_48 = io_a[24] ^ io_b[24];
  wire _absDiff_T_50 = io_a[25] ^ io_b[25];
  wire _absDiff_T_52 = io_a[26] ^ io_b[26];
  wire _absDiff_T_54 = io_a[27] ^ io_b[27];
  wire _absDiff_T_56 = io_a[28] ^ io_b[28];
  wire _absDiff_T_58 = io_a[29] ^ io_b[29];
  wire _absDiff_T_60 = io_a[30] ^ io_b[30];
  wire _absDiff_T_62 = io_a[31] ^ io_b[31];
  wire _absDiff_T_64 = io_a[32] ^ io_b[32];
  wire _absDiff_T_66 = io_a[33] ^ io_b[33];
  wire _absDiff_T_68 = io_a[34] ^ io_b[34];
  wire _absDiff_T_70 = io_a[35] ^ io_b[35];
  wire _absDiff_T_72 = io_a[36] ^ io_b[36];
  wire _absDiff_T_74 = io_a[37] ^ io_b[37];
  wire _absDiff_T_76 = io_a[38] ^ io_b[38];
  wire _absDiff_T_78 = io_a[39] ^ io_b[39];
  wire _absDiff_T_80 = io_a[40] ^ io_b[40];
  wire _absDiff_T_82 = io_a[41] ^ io_b[41];
  wire _absDiff_T_84 = io_a[42] ^ io_b[42];
  wire _absDiff_T_86 = io_a[43] ^ io_b[43];
  wire _absDiff_T_88 = io_a[44] ^ io_b[44];
  wire _absDiff_T_90 = io_a[45] ^ io_b[45];
  wire _absDiff_T_92 = io_a[46] ^ io_b[46];
  wire _absDiff_T_94 = io_a[47] ^ io_b[47];
  wire _absDiff_T_96 = io_a[48] ^ io_b[48];
  wire _absDiff_T_98 = io_a[49] ^ io_b[49];
  wire _absDiff_T_100 = io_a[50] ^ io_b[50];
  wire _absDiff_T_102 = io_a[51] ^ io_b[51];
  wire _absDiff_T_104 = io_a[52] ^ io_b[52];
  wire _absDiff_T_106 = io_a[53] ^ io_b[53];
  wire _absDiff_T_108 = io_a[54] ^ io_b[54];
  wire _absDiff_T_110 = io_a[55] ^ io_b[55];
  wire _absDiff_T_112 = io_a[56] ^ io_b[56];
  wire _absDiff_T_114 = io_a[57] ^ io_b[57];
  wire _absDiff_T_116 = io_a[58] ^ io_b[58];
  wire _absDiff_T_118 = io_a[59] ^ io_b[59];
  wire _absDiff_T_120 = io_a[60] ^ io_b[60];
  wire _absDiff_T_122 = io_a[61] ^ io_b[61];
  wire _absDiff_T_124 = io_a[62] ^ io_b[62];
  wire _absDiff_T_126 = io_a[63] ^ io_b[63];
  wire _absDiff_T_128 = io_a[64] ^ io_b[64];
  wire _absDiff_T_130 = io_a[65] ^ io_b[65];
  wire _absDiff_T_132 = io_a[66] ^ io_b[66];
  wire _absDiff_T_134 = io_a[67] ^ io_b[67];
  wire _absDiff_T_136 = io_a[68] ^ io_b[68];
  wire _absDiff_T_138 = io_a[69] ^ io_b[69];
  wire _absDiff_T_140 = io_a[70] ^ io_b[70];
  wire _absDiff_T_142 = io_a[71] ^ io_b[71];
  wire _absDiff_T_144 = io_a[72] ^ io_b[72];
  wire _absDiff_T_146 = io_a[73] ^ io_b[73];
  wire _absDiff_T_148 = io_a[74] ^ io_b[74];
  wire _absDiff_T_150 = io_a[75] ^ io_b[75];
  wire _absDiff_T_152 = io_a[76] ^ io_b[76];
  wire _absDiff_T_154 = io_a[77] ^ io_b[77];
  wire _absDiff_T_156 = io_a[78] ^ io_b[78];
  wire _absDiff_T_158 = io_a[79] ^ io_b[79];
  wire _absDiff_T_160 = io_a[80] ^ io_b[80];
  wire _absDiff_T_162 = io_a[81] ^ io_b[81];
  wire _absDiff_T_164 = io_a[82] ^ io_b[82];
  wire _absDiff_T_166 = io_a[83] ^ io_b[83];
  wire _absDiff_T_168 = io_a[84] ^ io_b[84];
  wire _absDiff_T_170 = io_a[85] ^ io_b[85];
  wire _absDiff_T_172 = io_a[86] ^ io_b[86];
  wire _absDiff_T_174 = io_a[87] ^ io_b[87];
  wire _absDiff_T_176 = io_a[88] ^ io_b[88];
  wire _absDiff_T_178 = io_a[89] ^ io_b[89];
  wire _absDiff_T_180 = io_a[90] ^ io_b[90];
  wire _absDiff_T_182 = io_a[91] ^ io_b[91];
  wire _absDiff_T_184 = io_a[92] ^ io_b[92];
  wire _absDiff_T_186 = io_a[93] ^ io_b[93];
  wire _absDiff_T_188 = io_a[94] ^ io_b[94];
  wire _absDiff_T_190 = io_a[95] ^ io_b[95];
  wire _absDiff_T_192 = io_a[96] ^ io_b[96];
  wire _absDiff_T_194 = io_a[97] ^ io_b[97];
  wire _absDiff_T_196 = io_a[98] ^ io_b[98];
  wire _absDiff_T_198 = io_a[99] ^ io_b[99];
  wire _absDiff_T_200 = io_a[100] ^ io_b[100];
  wire _absDiff_T_202 = io_a[101] ^ io_b[101];
  wire _absDiff_T_204 = io_a[102] ^ io_b[102];
  wire _absDiff_T_206 = io_a[103] ^ io_b[103];
  wire _absDiff_T_208 = io_a[104] ^ io_b[104];
  wire _GEN_0 = ~(io_a[1]) & io_b[1] | ~_absDiff_T_2 & _GEN;
  wire _GEN_1 = ~_absDiff_T_2 & ~_absDiff_WIRE_0;
  wire _GEN_2 = ~(io_a[2]) & io_b[2] | ~_absDiff_T_4 & _GEN_0;
  wire _GEN_3 = ~_absDiff_T_4 & _GEN_1;
  wire _GEN_4 = ~(io_a[3]) & io_b[3] | ~_absDiff_T_6 & _GEN_2;
  wire _GEN_5 = ~_absDiff_T_6 & _GEN_3;
  wire _GEN_6 = ~(io_a[4]) & io_b[4] | ~_absDiff_T_8 & _GEN_4;
  wire _GEN_7 = ~_absDiff_T_8 & _GEN_5;
  wire _GEN_8 = ~(io_a[5]) & io_b[5] | ~_absDiff_T_10 & _GEN_6;
  wire _GEN_9 = ~_absDiff_T_10 & _GEN_7;
  wire _GEN_10 = ~(io_a[6]) & io_b[6] | ~_absDiff_T_12 & _GEN_8;
  wire _GEN_11 = ~_absDiff_T_12 & _GEN_9;
  wire _GEN_12 = ~(io_a[7]) & io_b[7] | ~_absDiff_T_14 & _GEN_10;
  wire _GEN_13 = ~_absDiff_T_14 & _GEN_11;
  wire _GEN_14 = ~(io_a[8]) & io_b[8] | ~_absDiff_T_16 & _GEN_12;
  wire _GEN_15 = ~_absDiff_T_16 & _GEN_13;
  wire _GEN_16 = ~(io_a[9]) & io_b[9] | ~_absDiff_T_18 & _GEN_14;
  wire _GEN_17 = ~_absDiff_T_18 & _GEN_15;
  wire _GEN_18 = ~(io_a[10]) & io_b[10] | ~_absDiff_T_20 & _GEN_16;
  wire _GEN_19 = ~_absDiff_T_20 & _GEN_17;
  wire _GEN_20 = ~(io_a[11]) & io_b[11] | ~_absDiff_T_22 & _GEN_18;
  wire _GEN_21 = ~_absDiff_T_22 & _GEN_19;
  wire _GEN_22 = ~(io_a[12]) & io_b[12] | ~_absDiff_T_24 & _GEN_20;
  wire _GEN_23 = ~_absDiff_T_24 & _GEN_21;
  wire _GEN_24 = ~(io_a[13]) & io_b[13] | ~_absDiff_T_26 & _GEN_22;
  wire _GEN_25 = ~_absDiff_T_26 & _GEN_23;
  wire _GEN_26 = ~(io_a[14]) & io_b[14] | ~_absDiff_T_28 & _GEN_24;
  wire _GEN_27 = ~_absDiff_T_28 & _GEN_25;
  wire _GEN_28 = ~(io_a[15]) & io_b[15] | ~_absDiff_T_30 & _GEN_26;
  wire _GEN_29 = ~_absDiff_T_30 & _GEN_27;
  wire _GEN_30 = ~(io_a[16]) & io_b[16] | ~_absDiff_T_32 & _GEN_28;
  wire _GEN_31 = ~_absDiff_T_32 & _GEN_29;
  wire _GEN_32 = ~(io_a[17]) & io_b[17] | ~_absDiff_T_34 & _GEN_30;
  wire _GEN_33 = ~_absDiff_T_34 & _GEN_31;
  wire _GEN_34 = ~(io_a[18]) & io_b[18] | ~_absDiff_T_36 & _GEN_32;
  wire _GEN_35 = ~_absDiff_T_36 & _GEN_33;
  wire _GEN_36 = ~(io_a[19]) & io_b[19] | ~_absDiff_T_38 & _GEN_34;
  wire _GEN_37 = ~_absDiff_T_38 & _GEN_35;
  wire _GEN_38 = ~(io_a[20]) & io_b[20] | ~_absDiff_T_40 & _GEN_36;
  wire _GEN_39 = ~_absDiff_T_40 & _GEN_37;
  wire _GEN_40 = ~(io_a[21]) & io_b[21] | ~_absDiff_T_42 & _GEN_38;
  wire _GEN_41 = ~_absDiff_T_42 & _GEN_39;
  wire _GEN_42 = ~(io_a[22]) & io_b[22] | ~_absDiff_T_44 & _GEN_40;
  wire _GEN_43 = ~_absDiff_T_44 & _GEN_41;
  wire _GEN_44 = ~(io_a[23]) & io_b[23] | ~_absDiff_T_46 & _GEN_42;
  wire _GEN_45 = ~_absDiff_T_46 & _GEN_43;
  wire _GEN_46 = ~(io_a[24]) & io_b[24] | ~_absDiff_T_48 & _GEN_44;
  wire _GEN_47 = ~_absDiff_T_48 & _GEN_45;
  wire _GEN_48 = ~(io_a[25]) & io_b[25] | ~_absDiff_T_50 & _GEN_46;
  wire _GEN_49 = ~_absDiff_T_50 & _GEN_47;
  wire _GEN_50 = ~(io_a[26]) & io_b[26] | ~_absDiff_T_52 & _GEN_48;
  wire _GEN_51 = ~_absDiff_T_52 & _GEN_49;
  wire _GEN_52 = ~(io_a[27]) & io_b[27] | ~_absDiff_T_54 & _GEN_50;
  wire _GEN_53 = ~_absDiff_T_54 & _GEN_51;
  wire _GEN_54 = ~(io_a[28]) & io_b[28] | ~_absDiff_T_56 & _GEN_52;
  wire _GEN_55 = ~_absDiff_T_56 & _GEN_53;
  wire _GEN_56 = ~(io_a[29]) & io_b[29] | ~_absDiff_T_58 & _GEN_54;
  wire _GEN_57 = ~_absDiff_T_58 & _GEN_55;
  wire _GEN_58 = ~(io_a[30]) & io_b[30] | ~_absDiff_T_60 & _GEN_56;
  wire _GEN_59 = ~_absDiff_T_60 & _GEN_57;
  wire _GEN_60 = ~(io_a[31]) & io_b[31] | ~_absDiff_T_62 & _GEN_58;
  wire _GEN_61 = ~_absDiff_T_62 & _GEN_59;
  wire _GEN_62 = ~(io_a[32]) & io_b[32] | ~_absDiff_T_64 & _GEN_60;
  wire _GEN_63 = ~_absDiff_T_64 & _GEN_61;
  wire _GEN_64 = ~(io_a[33]) & io_b[33] | ~_absDiff_T_66 & _GEN_62;
  wire _GEN_65 = ~_absDiff_T_66 & _GEN_63;
  wire _GEN_66 = ~(io_a[34]) & io_b[34] | ~_absDiff_T_68 & _GEN_64;
  wire _GEN_67 = ~_absDiff_T_68 & _GEN_65;
  wire _GEN_68 = ~(io_a[35]) & io_b[35] | ~_absDiff_T_70 & _GEN_66;
  wire _GEN_69 = ~_absDiff_T_70 & _GEN_67;
  wire _GEN_70 = ~(io_a[36]) & io_b[36] | ~_absDiff_T_72 & _GEN_68;
  wire _GEN_71 = ~_absDiff_T_72 & _GEN_69;
  wire _GEN_72 = ~(io_a[37]) & io_b[37] | ~_absDiff_T_74 & _GEN_70;
  wire _GEN_73 = ~_absDiff_T_74 & _GEN_71;
  wire _GEN_74 = ~(io_a[38]) & io_b[38] | ~_absDiff_T_76 & _GEN_72;
  wire _GEN_75 = ~_absDiff_T_76 & _GEN_73;
  wire _GEN_76 = ~(io_a[39]) & io_b[39] | ~_absDiff_T_78 & _GEN_74;
  wire _GEN_77 = ~_absDiff_T_78 & _GEN_75;
  wire _GEN_78 = ~(io_a[40]) & io_b[40] | ~_absDiff_T_80 & _GEN_76;
  wire _GEN_79 = ~_absDiff_T_80 & _GEN_77;
  wire _GEN_80 = ~(io_a[41]) & io_b[41] | ~_absDiff_T_82 & _GEN_78;
  wire _GEN_81 = ~_absDiff_T_82 & _GEN_79;
  wire _GEN_82 = ~(io_a[42]) & io_b[42] | ~_absDiff_T_84 & _GEN_80;
  wire _GEN_83 = ~_absDiff_T_84 & _GEN_81;
  wire _GEN_84 = ~(io_a[43]) & io_b[43] | ~_absDiff_T_86 & _GEN_82;
  wire _GEN_85 = ~_absDiff_T_86 & _GEN_83;
  wire _GEN_86 = ~(io_a[44]) & io_b[44] | ~_absDiff_T_88 & _GEN_84;
  wire _GEN_87 = ~_absDiff_T_88 & _GEN_85;
  wire _GEN_88 = ~(io_a[45]) & io_b[45] | ~_absDiff_T_90 & _GEN_86;
  wire _GEN_89 = ~_absDiff_T_90 & _GEN_87;
  wire _GEN_90 = ~(io_a[46]) & io_b[46] | ~_absDiff_T_92 & _GEN_88;
  wire _GEN_91 = ~_absDiff_T_92 & _GEN_89;
  wire _GEN_92 = ~(io_a[47]) & io_b[47] | ~_absDiff_T_94 & _GEN_90;
  wire _GEN_93 = ~_absDiff_T_94 & _GEN_91;
  wire _GEN_94 = ~(io_a[48]) & io_b[48] | ~_absDiff_T_96 & _GEN_92;
  wire _GEN_95 = ~_absDiff_T_96 & _GEN_93;
  wire _GEN_96 = ~(io_a[49]) & io_b[49] | ~_absDiff_T_98 & _GEN_94;
  wire _GEN_97 = ~_absDiff_T_98 & _GEN_95;
  wire _GEN_98 = ~(io_a[50]) & io_b[50] | ~_absDiff_T_100 & _GEN_96;
  wire _GEN_99 = ~_absDiff_T_100 & _GEN_97;
  wire _GEN_100 = ~(io_a[51]) & io_b[51] | ~_absDiff_T_102 & _GEN_98;
  wire _GEN_101 = ~_absDiff_T_102 & _GEN_99;
  wire _GEN_102 = ~(io_a[52]) & io_b[52] | ~_absDiff_T_104 & _GEN_100;
  wire _GEN_103 = ~_absDiff_T_104 & _GEN_101;
  wire _GEN_104 = ~(io_a[53]) & io_b[53] | ~_absDiff_T_106 & _GEN_102;
  wire _GEN_105 = ~_absDiff_T_106 & _GEN_103;
  wire _GEN_106 = ~(io_a[54]) & io_b[54] | ~_absDiff_T_108 & _GEN_104;
  wire _GEN_107 = ~_absDiff_T_108 & _GEN_105;
  wire _GEN_108 = ~(io_a[55]) & io_b[55] | ~_absDiff_T_110 & _GEN_106;
  wire _GEN_109 = ~_absDiff_T_110 & _GEN_107;
  wire _GEN_110 = ~(io_a[56]) & io_b[56] | ~_absDiff_T_112 & _GEN_108;
  wire _GEN_111 = ~_absDiff_T_112 & _GEN_109;
  wire _GEN_112 = ~(io_a[57]) & io_b[57] | ~_absDiff_T_114 & _GEN_110;
  wire _GEN_113 = ~_absDiff_T_114 & _GEN_111;
  wire _GEN_114 = ~(io_a[58]) & io_b[58] | ~_absDiff_T_116 & _GEN_112;
  wire _GEN_115 = ~_absDiff_T_116 & _GEN_113;
  wire _GEN_116 = ~(io_a[59]) & io_b[59] | ~_absDiff_T_118 & _GEN_114;
  wire _GEN_117 = ~_absDiff_T_118 & _GEN_115;
  wire _GEN_118 = ~(io_a[60]) & io_b[60] | ~_absDiff_T_120 & _GEN_116;
  wire _GEN_119 = ~_absDiff_T_120 & _GEN_117;
  wire _GEN_120 = ~(io_a[61]) & io_b[61] | ~_absDiff_T_122 & _GEN_118;
  wire _GEN_121 = ~_absDiff_T_122 & _GEN_119;
  wire _GEN_122 = ~(io_a[62]) & io_b[62] | ~_absDiff_T_124 & _GEN_120;
  wire _GEN_123 = ~_absDiff_T_124 & _GEN_121;
  wire _GEN_124 = ~(io_a[63]) & io_b[63] | ~_absDiff_T_126 & _GEN_122;
  wire _GEN_125 = ~_absDiff_T_126 & _GEN_123;
  wire _GEN_126 = ~(io_a[64]) & io_b[64] | ~_absDiff_T_128 & _GEN_124;
  wire _GEN_127 = ~_absDiff_T_128 & _GEN_125;
  wire _GEN_128 = ~(io_a[65]) & io_b[65] | ~_absDiff_T_130 & _GEN_126;
  wire _GEN_129 = ~_absDiff_T_130 & _GEN_127;
  wire _GEN_130 = ~(io_a[66]) & io_b[66] | ~_absDiff_T_132 & _GEN_128;
  wire _GEN_131 = ~_absDiff_T_132 & _GEN_129;
  wire _GEN_132 = ~(io_a[67]) & io_b[67] | ~_absDiff_T_134 & _GEN_130;
  wire _GEN_133 = ~_absDiff_T_134 & _GEN_131;
  wire _GEN_134 = ~(io_a[68]) & io_b[68] | ~_absDiff_T_136 & _GEN_132;
  wire _GEN_135 = ~_absDiff_T_136 & _GEN_133;
  wire _GEN_136 = ~(io_a[69]) & io_b[69] | ~_absDiff_T_138 & _GEN_134;
  wire _GEN_137 = ~_absDiff_T_138 & _GEN_135;
  wire _GEN_138 = ~(io_a[70]) & io_b[70] | ~_absDiff_T_140 & _GEN_136;
  wire _GEN_139 = ~_absDiff_T_140 & _GEN_137;
  wire _GEN_140 = ~(io_a[71]) & io_b[71] | ~_absDiff_T_142 & _GEN_138;
  wire _GEN_141 = ~_absDiff_T_142 & _GEN_139;
  wire _GEN_142 = ~(io_a[72]) & io_b[72] | ~_absDiff_T_144 & _GEN_140;
  wire _GEN_143 = ~_absDiff_T_144 & _GEN_141;
  wire _GEN_144 = ~(io_a[73]) & io_b[73] | ~_absDiff_T_146 & _GEN_142;
  wire _GEN_145 = ~_absDiff_T_146 & _GEN_143;
  wire _GEN_146 = ~(io_a[74]) & io_b[74] | ~_absDiff_T_148 & _GEN_144;
  wire _GEN_147 = ~_absDiff_T_148 & _GEN_145;
  wire _GEN_148 = ~(io_a[75]) & io_b[75] | ~_absDiff_T_150 & _GEN_146;
  wire _GEN_149 = ~_absDiff_T_150 & _GEN_147;
  wire _GEN_150 = ~(io_a[76]) & io_b[76] | ~_absDiff_T_152 & _GEN_148;
  wire _GEN_151 = ~_absDiff_T_152 & _GEN_149;
  wire _GEN_152 = ~(io_a[77]) & io_b[77] | ~_absDiff_T_154 & _GEN_150;
  wire _GEN_153 = ~_absDiff_T_154 & _GEN_151;
  wire _GEN_154 = ~(io_a[78]) & io_b[78] | ~_absDiff_T_156 & _GEN_152;
  wire _GEN_155 = ~_absDiff_T_156 & _GEN_153;
  wire _GEN_156 = ~(io_a[79]) & io_b[79] | ~_absDiff_T_158 & _GEN_154;
  wire _GEN_157 = ~_absDiff_T_158 & _GEN_155;
  wire _GEN_158 = ~(io_a[80]) & io_b[80] | ~_absDiff_T_160 & _GEN_156;
  wire _GEN_159 = ~_absDiff_T_160 & _GEN_157;
  wire _GEN_160 = ~(io_a[81]) & io_b[81] | ~_absDiff_T_162 & _GEN_158;
  wire _GEN_161 = ~_absDiff_T_162 & _GEN_159;
  wire _GEN_162 = ~(io_a[82]) & io_b[82] | ~_absDiff_T_164 & _GEN_160;
  wire _GEN_163 = ~_absDiff_T_164 & _GEN_161;
  wire _GEN_164 = ~(io_a[83]) & io_b[83] | ~_absDiff_T_166 & _GEN_162;
  wire _GEN_165 = ~_absDiff_T_166 & _GEN_163;
  wire _GEN_166 = ~(io_a[84]) & io_b[84] | ~_absDiff_T_168 & _GEN_164;
  wire _GEN_167 = ~_absDiff_T_168 & _GEN_165;
  wire _GEN_168 = ~(io_a[85]) & io_b[85] | ~_absDiff_T_170 & _GEN_166;
  wire _GEN_169 = ~_absDiff_T_170 & _GEN_167;
  wire _GEN_170 = ~(io_a[86]) & io_b[86] | ~_absDiff_T_172 & _GEN_168;
  wire _GEN_171 = ~_absDiff_T_172 & _GEN_169;
  wire _GEN_172 = ~(io_a[87]) & io_b[87] | ~_absDiff_T_174 & _GEN_170;
  wire _GEN_173 = ~_absDiff_T_174 & _GEN_171;
  wire _GEN_174 = ~(io_a[88]) & io_b[88] | ~_absDiff_T_176 & _GEN_172;
  wire _GEN_175 = ~_absDiff_T_176 & _GEN_173;
  wire _GEN_176 = ~(io_a[89]) & io_b[89] | ~_absDiff_T_178 & _GEN_174;
  wire _GEN_177 = ~_absDiff_T_178 & _GEN_175;
  wire _GEN_178 = ~(io_a[90]) & io_b[90] | ~_absDiff_T_180 & _GEN_176;
  wire _GEN_179 = ~_absDiff_T_180 & _GEN_177;
  wire _GEN_180 = ~(io_a[91]) & io_b[91] | ~_absDiff_T_182 & _GEN_178;
  wire _GEN_181 = ~_absDiff_T_182 & _GEN_179;
  wire _GEN_182 = ~(io_a[92]) & io_b[92] | ~_absDiff_T_184 & _GEN_180;
  wire _GEN_183 = ~_absDiff_T_184 & _GEN_181;
  wire _GEN_184 = ~(io_a[93]) & io_b[93] | ~_absDiff_T_186 & _GEN_182;
  wire _GEN_185 = ~_absDiff_T_186 & _GEN_183;
  wire _GEN_186 = ~(io_a[94]) & io_b[94] | ~_absDiff_T_188 & _GEN_184;
  wire _GEN_187 = ~_absDiff_T_188 & _GEN_185;
  wire _GEN_188 = ~(io_a[95]) & io_b[95] | ~_absDiff_T_190 & _GEN_186;
  wire _GEN_189 = ~_absDiff_T_190 & _GEN_187;
  wire _GEN_190 = ~(io_a[96]) & io_b[96] | ~_absDiff_T_192 & _GEN_188;
  wire _GEN_191 = ~_absDiff_T_192 & _GEN_189;
  wire _GEN_192 = ~(io_a[97]) & io_b[97] | ~_absDiff_T_194 & _GEN_190;
  wire _GEN_193 = ~_absDiff_T_194 & _GEN_191;
  wire _GEN_194 = ~(io_a[98]) & io_b[98] | ~_absDiff_T_196 & _GEN_192;
  wire _GEN_195 = ~_absDiff_T_196 & _GEN_193;
  wire _GEN_196 = ~(io_a[99]) & io_b[99] | ~_absDiff_T_198 & _GEN_194;
  wire _GEN_197 = ~_absDiff_T_198 & _GEN_195;
  wire _GEN_198 = ~(io_a[100]) & io_b[100] | ~_absDiff_T_200 & _GEN_196;
  wire _GEN_199 = ~_absDiff_T_200 & _GEN_197;
  wire _GEN_200 = ~(io_a[101]) & io_b[101] | ~_absDiff_T_202 & _GEN_198;
  wire _GEN_201 = ~_absDiff_T_202 & _GEN_199;
  wire _GEN_202 = ~(io_a[102]) & io_b[102] | ~_absDiff_T_204 & _GEN_200;
  wire _GEN_203 = ~_absDiff_T_204 & _GEN_201;
  wire _GEN_204 = ~(io_a[103]) & io_b[103] | ~_absDiff_T_206 & _GEN_202;
  wire lt = ~(io_a[104]) & io_b[104] | ~_absDiff_T_208 & _GEN_204;
  assign io_lt = lt;
  assign io_absDiff =
    {_absDiff_T_208 ^ _GEN_204 ^ lt & ~(~_absDiff_T_206 & _GEN_203),
     _absDiff_T_206 ^ _GEN_202 ^ lt & ~_GEN_203,
     _absDiff_T_204 ^ _GEN_200 ^ lt & ~_GEN_201,
     _absDiff_T_202 ^ _GEN_198 ^ lt & ~_GEN_199,
     _absDiff_T_200 ^ _GEN_196 ^ lt & ~_GEN_197,
     _absDiff_T_198 ^ _GEN_194 ^ lt & ~_GEN_195,
     _absDiff_T_196 ^ _GEN_192 ^ lt & ~_GEN_193,
     _absDiff_T_194 ^ _GEN_190 ^ lt & ~_GEN_191,
     _absDiff_T_192 ^ _GEN_188 ^ lt & ~_GEN_189,
     _absDiff_T_190 ^ _GEN_186 ^ lt & ~_GEN_187,
     _absDiff_T_188 ^ _GEN_184 ^ lt & ~_GEN_185,
     _absDiff_T_186 ^ _GEN_182 ^ lt & ~_GEN_183,
     _absDiff_T_184 ^ _GEN_180 ^ lt & ~_GEN_181,
     _absDiff_T_182 ^ _GEN_178 ^ lt & ~_GEN_179,
     _absDiff_T_180 ^ _GEN_176 ^ lt & ~_GEN_177,
     _absDiff_T_178 ^ _GEN_174 ^ lt & ~_GEN_175,
     _absDiff_T_176 ^ _GEN_172 ^ lt & ~_GEN_173,
     _absDiff_T_174 ^ _GEN_170 ^ lt & ~_GEN_171,
     _absDiff_T_172 ^ _GEN_168 ^ lt & ~_GEN_169,
     _absDiff_T_170 ^ _GEN_166 ^ lt & ~_GEN_167,
     _absDiff_T_168 ^ _GEN_164 ^ lt & ~_GEN_165,
     _absDiff_T_166 ^ _GEN_162 ^ lt & ~_GEN_163,
     _absDiff_T_164 ^ _GEN_160 ^ lt & ~_GEN_161,
     _absDiff_T_162 ^ _GEN_158 ^ lt & ~_GEN_159,
     _absDiff_T_160 ^ _GEN_156 ^ lt & ~_GEN_157,
     _absDiff_T_158 ^ _GEN_154 ^ lt & ~_GEN_155,
     _absDiff_T_156 ^ _GEN_152 ^ lt & ~_GEN_153,
     _absDiff_T_154 ^ _GEN_150 ^ lt & ~_GEN_151,
     _absDiff_T_152 ^ _GEN_148 ^ lt & ~_GEN_149,
     _absDiff_T_150 ^ _GEN_146 ^ lt & ~_GEN_147,
     _absDiff_T_148 ^ _GEN_144 ^ lt & ~_GEN_145,
     _absDiff_T_146 ^ _GEN_142 ^ lt & ~_GEN_143,
     _absDiff_T_144 ^ _GEN_140 ^ lt & ~_GEN_141,
     _absDiff_T_142 ^ _GEN_138 ^ lt & ~_GEN_139,
     _absDiff_T_140 ^ _GEN_136 ^ lt & ~_GEN_137,
     _absDiff_T_138 ^ _GEN_134 ^ lt & ~_GEN_135,
     _absDiff_T_136 ^ _GEN_132 ^ lt & ~_GEN_133,
     _absDiff_T_134 ^ _GEN_130 ^ lt & ~_GEN_131,
     _absDiff_T_132 ^ _GEN_128 ^ lt & ~_GEN_129,
     _absDiff_T_130 ^ _GEN_126 ^ lt & ~_GEN_127,
     _absDiff_T_128 ^ _GEN_124 ^ lt & ~_GEN_125,
     _absDiff_T_126 ^ _GEN_122 ^ lt & ~_GEN_123,
     _absDiff_T_124 ^ _GEN_120 ^ lt & ~_GEN_121,
     _absDiff_T_122 ^ _GEN_118 ^ lt & ~_GEN_119,
     _absDiff_T_120 ^ _GEN_116 ^ lt & ~_GEN_117,
     _absDiff_T_118 ^ _GEN_114 ^ lt & ~_GEN_115,
     _absDiff_T_116 ^ _GEN_112 ^ lt & ~_GEN_113,
     _absDiff_T_114 ^ _GEN_110 ^ lt & ~_GEN_111,
     _absDiff_T_112 ^ _GEN_108 ^ lt & ~_GEN_109,
     _absDiff_T_110 ^ _GEN_106 ^ lt & ~_GEN_107,
     _absDiff_T_108 ^ _GEN_104 ^ lt & ~_GEN_105,
     _absDiff_T_106 ^ _GEN_102 ^ lt & ~_GEN_103,
     _absDiff_T_104 ^ _GEN_100 ^ lt & ~_GEN_101,
     _absDiff_T_102 ^ _GEN_98 ^ lt & ~_GEN_99,
     _absDiff_T_100 ^ _GEN_96 ^ lt & ~_GEN_97,
     _absDiff_T_98 ^ _GEN_94 ^ lt & ~_GEN_95,
     _absDiff_T_96 ^ _GEN_92 ^ lt & ~_GEN_93,
     _absDiff_T_94 ^ _GEN_90 ^ lt & ~_GEN_91,
     _absDiff_T_92 ^ _GEN_88 ^ lt & ~_GEN_89,
     _absDiff_T_90 ^ _GEN_86 ^ lt & ~_GEN_87,
     _absDiff_T_88 ^ _GEN_84 ^ lt & ~_GEN_85,
     _absDiff_T_86 ^ _GEN_82 ^ lt & ~_GEN_83,
     _absDiff_T_84 ^ _GEN_80 ^ lt & ~_GEN_81,
     _absDiff_T_82 ^ _GEN_78 ^ lt & ~_GEN_79,
     _absDiff_T_80 ^ _GEN_76 ^ lt & ~_GEN_77,
     _absDiff_T_78 ^ _GEN_74 ^ lt & ~_GEN_75,
     _absDiff_T_76 ^ _GEN_72 ^ lt & ~_GEN_73,
     _absDiff_T_74 ^ _GEN_70 ^ lt & ~_GEN_71,
     _absDiff_T_72 ^ _GEN_68 ^ lt & ~_GEN_69,
     _absDiff_T_70 ^ _GEN_66 ^ lt & ~_GEN_67,
     _absDiff_T_68 ^ _GEN_64 ^ lt & ~_GEN_65,
     _absDiff_T_66 ^ _GEN_62 ^ lt & ~_GEN_63,
     _absDiff_T_64 ^ _GEN_60 ^ lt & ~_GEN_61,
     _absDiff_T_62 ^ _GEN_58 ^ lt & ~_GEN_59,
     _absDiff_T_60 ^ _GEN_56 ^ lt & ~_GEN_57,
     _absDiff_T_58 ^ _GEN_54 ^ lt & ~_GEN_55,
     _absDiff_T_56 ^ _GEN_52 ^ lt & ~_GEN_53,
     _absDiff_T_54 ^ _GEN_50 ^ lt & ~_GEN_51,
     _absDiff_T_52 ^ _GEN_48 ^ lt & ~_GEN_49,
     _absDiff_T_50 ^ _GEN_46 ^ lt & ~_GEN_47,
     _absDiff_T_48 ^ _GEN_44 ^ lt & ~_GEN_45,
     _absDiff_T_46 ^ _GEN_42 ^ lt & ~_GEN_43,
     _absDiff_T_44 ^ _GEN_40 ^ lt & ~_GEN_41,
     _absDiff_T_42 ^ _GEN_38 ^ lt & ~_GEN_39,
     _absDiff_T_40 ^ _GEN_36 ^ lt & ~_GEN_37,
     _absDiff_T_38 ^ _GEN_34 ^ lt & ~_GEN_35,
     _absDiff_T_36 ^ _GEN_32 ^ lt & ~_GEN_33,
     _absDiff_T_34 ^ _GEN_30 ^ lt & ~_GEN_31,
     _absDiff_T_32 ^ _GEN_28 ^ lt & ~_GEN_29,
     _absDiff_T_30 ^ _GEN_26 ^ lt & ~_GEN_27,
     _absDiff_T_28 ^ _GEN_24 ^ lt & ~_GEN_25,
     _absDiff_T_26 ^ _GEN_22 ^ lt & ~_GEN_23,
     _absDiff_T_24 ^ _GEN_20 ^ lt & ~_GEN_21,
     _absDiff_T_22 ^ _GEN_18 ^ lt & ~_GEN_19,
     _absDiff_T_20 ^ _GEN_16 ^ lt & ~_GEN_17,
     _absDiff_T_18 ^ _GEN_14 ^ lt & ~_GEN_15,
     _absDiff_T_16 ^ _GEN_12 ^ lt & ~_GEN_13,
     _absDiff_T_14 ^ _GEN_10 ^ lt & ~_GEN_11,
     _absDiff_T_12 ^ _GEN_8 ^ lt & ~_GEN_9,
     _absDiff_T_10 ^ _GEN_6 ^ lt & ~_GEN_7,
     _absDiff_T_8 ^ _GEN_4 ^ lt & ~_GEN_5,
     _absDiff_T_6 ^ _GEN_2 ^ lt & ~_GEN_3,
     _absDiff_T_4 ^ _GEN_0 ^ lt & ~_GEN_1,
     _absDiff_T_2 ^ _GEN ^ lt & _absDiff_WIRE_0,
     _absDiff_WIRE_0};
endmodule

