// Generated by CIRCT firtool-1.138.0
module PrefixAdder(
  input  [1:0] io_a,
               io_b,
  input        io_cin,
  output [1:0] io_sum,
  output       io_cout
);

  wire _GEN = io_a[0] & io_b[0];
  wire _GEN_0 = io_a[0] ^ io_b[0];
  wire _GEN_1 = io_a[1] ^ io_b[1];
  assign io_sum = {_GEN_1 ^ (_GEN | _GEN_0 & io_cin), _GEN_0 ^ io_cin};
  assign io_cout = io_a[1] & io_b[1] | _GEN_1 & _GEN | _GEN_1 & _GEN_0 & io_cin;
endmodule

