// Generated by CIRCT firtool-1.138.0
module PrefixAbsDiff(
  input  [10:0] io_a,
                io_b,
  output        io_lt,
  output [10:0] io_absDiff
);

  wire _GEN = ~(io_a[0]) & io_b[0];
  wire _absDiff_WIRE_0 = io_a[0] ^ io_b[0];
  wire _absDiff_T_2 = io_a[1] ^ io_b[1];
  wire _absDiff_T_4 = io_a[2] ^ io_b[2];
  wire _absDiff_T_6 = io_a[3] ^ io_b[3];
  wire _absDiff_T_8 = io_a[4] ^ io_b[4];
  wire _absDiff_T_10 = io_a[5] ^ io_b[5];
  wire _absDiff_T_12 = io_a[6] ^ io_b[6];
  wire _absDiff_T_14 = io_a[7] ^ io_b[7];
  wire _absDiff_T_16 = io_a[8] ^ io_b[8];
  wire _absDiff_T_18 = io_a[9] ^ io_b[9];
  wire _absDiff_T_20 = io_a[10] ^ io_b[10];
  wire _GEN_0 = ~(io_a[1]) & io_b[1] | ~_absDiff_T_2 & _GEN;
  wire _GEN_1 = ~_absDiff_T_2 & ~_absDiff_WIRE_0;
  wire _GEN_2 = ~(io_a[2]) & io_b[2] | ~_absDiff_T_4 & _GEN_0;
  wire _GEN_3 = ~_absDiff_T_4 & _GEN_1;
  wire _GEN_4 = ~(io_a[3]) & io_b[3] | ~_absDiff_T_6 & _GEN_2;
  wire _GEN_5 = ~_absDiff_T_6 & _GEN_3;
  wire _GEN_6 = ~(io_a[4]) & io_b[4] | ~_absDiff_T_8 & _GEN_4;
  wire _GEN_7 = ~_absDiff_T_8 & _GEN_5;
  wire _GEN_8 = ~(io_a[5]) & io_b[5] | ~_absDiff_T_10 & _GEN_6;
  wire _GEN_9 = ~_absDiff_T_10 & _GEN_7;
  wire _GEN_10 = ~(io_a[6]) & io_b[6] | ~_absDiff_T_12 & _GEN_8;
  wire _GEN_11 = ~_absDiff_T_12 & _GEN_9;
  wire _GEN_12 = ~(io_a[7]) & io_b[7] | ~_absDiff_T_14 & _GEN_10;
  wire _GEN_13 = ~_absDiff_T_14 & _GEN_11;
  wire _GEN_14 = ~(io_a[8]) & io_b[8] | ~_absDiff_T_16 & _GEN_12;
  wire _GEN_15 = ~_absDiff_T_16 & _GEN_13;
  wire _GEN_16 = ~(io_a[9]) & io_b[9] | ~_absDiff_T_18 & _GEN_14;
  wire lt = ~(io_a[10]) & io_b[10] | ~_absDiff_T_20 & _GEN_16;
  assign io_lt = lt;
  assign io_absDiff =
    {_absDiff_T_20 ^ _GEN_16 ^ lt & ~(~_absDiff_T_18 & _GEN_15),
     _absDiff_T_18 ^ _GEN_14 ^ lt & ~_GEN_15,
     _absDiff_T_16 ^ _GEN_12 ^ lt & ~_GEN_13,
     _absDiff_T_14 ^ _GEN_10 ^ lt & ~_GEN_11,
     _absDiff_T_12 ^ _GEN_8 ^ lt & ~_GEN_9,
     _absDiff_T_10 ^ _GEN_6 ^ lt & ~_GEN_7,
     _absDiff_T_8 ^ _GEN_4 ^ lt & ~_GEN_5,
     _absDiff_T_6 ^ _GEN_2 ^ lt & ~_GEN_3,
     _absDiff_T_4 ^ _GEN_0 ^ lt & ~_GEN_1,
     _absDiff_T_2 ^ _GEN ^ lt & _absDiff_WIRE_0,
     _absDiff_WIRE_0};
endmodule

