// Generated by CIRCT firtool-1.138.0
module PrefixAdder(
  input  [3:0] io_a,
               io_b,
  input        io_cin,
  output [3:0] io_sum,
  output       io_cout
);

  wire _GEN = io_a[0] & io_b[0];
  wire _GEN_0 = io_a[0] ^ io_b[0];
  wire _GEN_1 = io_a[1] & io_b[1];
  wire _GEN_2 = io_a[1] ^ io_b[1];
  wire _GEN_3 = io_a[2] & io_b[2];
  wire _GEN_4 = io_a[2] ^ io_b[2];
  wire _GEN_5 = io_a[3] ^ io_b[3];
  wire _GEN_6 = _GEN_5 & _GEN_4;
  wire _GEN_7 = _GEN_6 & _GEN_2;
  wire _GEN_8 = _GEN_1 | _GEN_2 & _GEN;
  wire _GEN_9 = _GEN_2 & _GEN_0;
  assign io_sum =
    {_GEN_5 ^ (_GEN_3 | _GEN_4 & _GEN_8 | _GEN_4 & _GEN_9 & io_cin),
     _GEN_4 ^ (_GEN_8 | _GEN_9 & io_cin),
     _GEN_2 ^ (_GEN | _GEN_0 & io_cin),
     _GEN_0 ^ io_cin};
  assign io_cout =
    io_a[3] & io_b[3] | _GEN_5 & _GEN_3 | _GEN_6 & _GEN_1 | _GEN_7 & _GEN | _GEN_7
    & _GEN_0 & io_cin;
endmodule

