// Generated by CIRCT firtool-1.138.0
module PrefixAbsDiff(
  input  [2:0] io_a,
               io_b,
  output       io_lt,
  output [2:0] io_absDiff
);

  wire _GEN = ~(io_a[0]) & io_b[0];
  wire _absDiff_WIRE_0 = io_a[0] ^ io_b[0];
  wire _GEN_0 = ~(io_a[1]) & io_b[1];
  wire _absDiff_T_2 = io_a[1] ^ io_b[1];
  wire _absDiff_T_4 = io_a[2] ^ io_b[2];
  wire lt =
    ~(io_a[2]) & io_b[2] | ~_absDiff_T_4 & _GEN_0 | ~_absDiff_T_4 & ~_absDiff_T_2 & _GEN;
  assign io_lt = lt;
  assign io_absDiff =
    {_absDiff_T_4 ^ (_GEN_0 | ~_absDiff_T_2 & _GEN) ^ lt
       & ~(~_absDiff_T_2 & ~_absDiff_WIRE_0),
     _absDiff_T_2 ^ _GEN ^ lt & _absDiff_WIRE_0,
     _absDiff_WIRE_0};
endmodule

