// Generated by CIRCT firtool-1.138.0
module PrefixAdder(
  input  [7:0] io_a,
               io_b,
  input        io_cin,
  output [7:0] io_sum,
  output       io_cout
);

  wire _GEN = io_a[0] & io_b[0];
  wire _GEN_0 = io_a[0] ^ io_b[0];
  wire _GEN_1 = io_a[1] ^ io_b[1];
  wire _GEN_2 = io_a[2] ^ io_b[2];
  wire _GEN_3 = io_a[3] ^ io_b[3];
  wire _GEN_4 = io_a[4] ^ io_b[4];
  wire _GEN_5 = io_a[5] ^ io_b[5];
  wire _GEN_6 = io_a[6] ^ io_b[6];
  wire _GEN_7 = io_a[7] ^ io_b[7];
  wire _GEN_8 = io_a[1] & io_b[1] | _GEN_1 & _GEN;
  wire _GEN_9 = _GEN_1 & _GEN_0;
  wire _GEN_10 = io_a[2] & io_b[2] | _GEN_2 & _GEN_8;
  wire _GEN_11 = _GEN_2 & _GEN_9;
  wire _GEN_12 = io_a[3] & io_b[3] | _GEN_3 & _GEN_10;
  wire _GEN_13 = _GEN_3 & _GEN_11;
  wire _GEN_14 = io_a[4] & io_b[4] | _GEN_4 & _GEN_12;
  wire _GEN_15 = _GEN_4 & _GEN_13;
  wire _GEN_16 = io_a[5] & io_b[5] | _GEN_5 & _GEN_14;
  wire _GEN_17 = _GEN_5 & _GEN_15;
  wire _GEN_18 = io_a[6] & io_b[6] | _GEN_6 & _GEN_16;
  wire _GEN_19 = _GEN_6 & _GEN_17;
  assign io_sum =
    {_GEN_7 ^ (_GEN_18 | _GEN_19 & io_cin),
     _GEN_6 ^ (_GEN_16 | _GEN_17 & io_cin),
     _GEN_5 ^ (_GEN_14 | _GEN_15 & io_cin),
     _GEN_4 ^ (_GEN_12 | _GEN_13 & io_cin),
     _GEN_3 ^ (_GEN_10 | _GEN_11 & io_cin),
     _GEN_2 ^ (_GEN_8 | _GEN_9 & io_cin),
     _GEN_1 ^ (_GEN | _GEN_0 & io_cin),
     _GEN_0 ^ io_cin};
  assign io_cout = io_a[7] & io_b[7] | _GEN_7 & _GEN_18 | _GEN_7 & _GEN_19 & io_cin;
endmodule

